(in-package cl-user)

;;;
;;;----------------------------------------------
;;;   Automatically Generated nRQL Symbol List   
;;;          Version: 2.0, Build: 2013-03-07 
;;;          Date: March 07 2013, 13:05  
;;;----------------------------------------------
;;;

(defpackage :nrql-symbols
  (:use :common-lisp)
  (:export 
   #:*owllink2-output-syntax*
   #:*owllink2-input-syntax*
   #:*converter-mode*
   #:*told-information-reasoning-p*
   #:*toggle-una-variables-p*
   #:*cur-reasoner*
   #:*cur-substrate*
   #:query
   #:IRI
   #:with-nrql-standard-settings
   #:racer-retrieve-individual-filled-roles
   #:racer-retrieve-individual-fillers
   #:racer-retrieve-related-individuals
   #:racer-dummy-substrate
   #:data-substrate
   #:mirror-data-substrate
   #:mirror-sql-data-substrate
   #:rcc-substrate
   #:rcc-mirror-substrate
   #:master-top-query
   #:master-bottom-query
   #:top-query
   #:bottom-query
   #:top-role
   #:bottom-role
   #:defer
   #:xml-output
   #:xml-input
   #:xml-native-output
   #:sequence
   #:answer-sequence
   #:quiet-sequence
   #:owlapi-sequence
   #:owlapi-test-sequence
   #:owlapi-answer-sequence
   #:owlapi-quiet-sequence
   #:|OWLAPI-sequence|
   #:|OWLAPI-testSequence|
   #:|OWLAPI-answerSequence|
   #:|OWLAPI-quietSequence|
   #:|OWLAPI-getLastAnswer|
   #:|OWLAPI-getIDsOfLastAnswer|
   #:|OWLAPI-getLastOutputStreamString|
   #:lisp-to-xml
   #:xml-to-lisp
   #:nrql-equal-role
   #:taxonomy-node
   #:has-synonym
   #:has-child
   #:has-parent
   #:has-descendant
   #:has-ancestor
   #:count
   #:sum
   #:prod
   #:avg
   #:substract
   #:div
   #:minilisp
   #:minilisp-server-function-p
   #:minilisp-server-value-p
   #:|OWLAxiom|
   #:|OWLLogicalAxiom|
   #:|OWLOntologyURIAttributeAxiom|
   #:|OWLAxiomWithEntitySlotAxiom|
   #:|OWLHasKeyAxiom|
   #:|OWLDatatypeDefinitionAxiom|
   #:|OWLPropertyAxiom|
   #:|OWLIndividualAxiom|
   #:|OWLClassAxiom|
   #:|OWLNaryDataPropertyAxiom|
   #:|OWLNaryObjectPropertyAxiom|
   #:|OWLDataPropertyAxiom|
   #:|OWLObjectPropertyAxiom|
   #:|OWLEquivalentDataPropertiesAxiom|
   #:|OWLDisjointDataPropertiesAxiom|
   #:|OWLInverseObjectPropertiesAxiom|
   #:|OWLEquivalentObjectPropertiesAxiom|
   #:|OWLDisjointObjectPropertiesAxiom|
   #:|OWLDataPropertyRangeAxiom|
   #:|OWLDataPropertyDomainAxiom|
   #:|OWLDataSubPropertyAxiom|
   #:|OWLFunctionalDataPropertyAxiom|
   #:|OWLObjectPropertyRangeAxiom|
   #:|OWLObjectPropertyDomainAxiom|
   #:|OWLObjectSubPropertyAxiom|
   #:|OWLTransitiveObjectPropertyAxiom|
   #:|OWLSymmetricObjectPropertyAxiom|
   #:|OWLReflexiveObjectPropertyAxiom|
   #:|OWLIrreflexiveObjectPropertyAxiom|
   #:|OWLInverseFunctionalObjectPropertyAxiom|
   #:|OWLAsymmetricObjectPropertyAxiom|
   #:|OWLAntiSymmetricObjectPropertyAxiom|
   #:|OWLObjectPropertyChainSubPropertyAxiom|
   #:|OWLFunctionalObjectPropertyAxiom|
   #:|OWLIndividualRelationshipAxiom|
   #:|OWLClassAssertionAxiom|
   #:|OWLNaryIndividualAxiom|
   #:|OWLObjectPropertyAssertionAxiom|
   #:|OWLDataPropertyAssertionAxiom|
   #:|OWLNegativeObjectPropertyAssertionAxiom|
   #:|OWLNegativeDataPropertyAssertionAxiom|
   #:|OWLSameIndividualsAxiom|
   #:|OWLDifferentIndividualsAxiom|
   #:|OWLNaryClassAxiom|
   #:|OWLSubClassAxiom|
   #:|OWLEquivalentClassesAxiom|
   #:|OWLDisjointUnionAxiom|
   #:|OWLDisjointClassesAxiom|
   #:|OWLPrefixDeclarationAxiom|
   #:|OWLOntologyVersionDeclarationAxiom|
   #:|OWLImportsDeclarationAxiom|
   #:|OWLDeclarationAxiom|
   #:|OWLAnnotationAxiom|
   #:|OWLImplicitDeclarationAxiom|
   #:|OWLAnnotationPropertyRangeAxiom|
   #:|OWLAnnotationPropertyDomainAxiom|
   #:|OWLSubAnnotationPropertyOfAxiom|
   #:|OWLAnnotationAssertionAxiom|
   #:|OWLOntologyAnnotationAxiom|
   #:|OWLEntityAnnotationAxiom|
   #:|OWLAxiomAnnotationAxiom|
   #:|SetOntologyURI|
   #:|OWLAxiomChange|
   #:|RemoveAxiom|
   #:|AddAxiom|
   #:|Reasoner|
   #:|WithReasoner|
   #:|Import|
   #:|Namespace|
   #:|Prefix|
   #:|Declaration|
   #:|Datatype|
   #:|OWLClass|
   #:|Class|
   #:|ObjectProperty|
   #:|DataProperty|
   #:|AnnotationProperty|
   #:|SubAnnotationPropertyOf|
   #:|AnnotationPropertyDomain|
   #:|AnnotationPropertyRange|
   #:|InverseObjectProperty|
   #:|ObjectInverseOf|
   #:|Individual|
   #:|NamedIndividual|
   #:|AnonymousIndividual|
   #:|Ontology|
   #:|Facet|
   #:|owl.Class|
   #:|owl.NamedIndividual|
   #:|owl.AnonymousIndividual|
   #:|owl.ObjectProperty|
   #:|owl.DataProperty|
   #:|owl.AnnotationProperty|
   #:|DataOneOf|
   #:|DataComplementOf|
   #:|DataIntersectionOf|
   #:|DataUnionOf|
   #:|DatatypeRestriction|
   #:|EntityAnnotation|
   #:|AnnotationAssertion|
   #:|ObjectUnionOf|
   #:|ObjectIntersectionOf|
   #:|ObjectComplementOf|
   #:|ObjectOneOf|
   #:|ObjectAllValuesFrom|
   #:|ObjectSomeValuesFrom|
   #:|ObjectExistsSelf|
   #:|ObjectHasSelf|
   #:|ObjectHasValue|
   #:|ObjectMaxCardinality|
   #:|ObjectMinCardinality|
   #:|ObjectExactCardinality|
   #:|DataAllValuesFrom|
   #:|DataSomeValuesFrom|
   #:|DataHasValue|
   #:|DataMaxCardinality|
   #:|DataMinCardinality|
   #:|EquivalentClasses|
   #:|DisjointClasses|
   #:|DisjointUnion|
   #:|SubObjectPropertyChain|
   #:|ObjectPropertyChain|
   #:|SubObjectPropertyOf|
   #:|EquivalentObjectProperties|
   #:|DisjointObjectProperties|
   #:|ObjectPropertyDomain|
   #:|ObjectPropertyRange|
   #:|InverseObjectProperties|
   #:|FunctionalObjectProperty|
   #:|InverseFunctionalObjectProperty|
   #:|ReflexiveObjectProperty|
   #:|IrreflexiveObjectProperty|
   #:|SymmetricObjectProperty|
   #:|AsymmetricObjectProperty|
   #:|TransitiveObjectProperty|
   #:|SubDataPropertyOf|
   #:|EquivalentDataProperties|
   #:|DisjointDataProperties|
   #:|DataPropertyDomain|
   #:|DataPropertyRange|
   #:|FunctionalDataProperty|
   #:|HasKey|
   #:|DatatypeDefinition|
   #:|SameIndividual|
   #:|SameIndividuals|
   #:|DifferentIndividual|
   #:|DifferentIndividuals|
   #:|ClassAssertion|
   #:|SubClassOf|
   #:|ObjectPropertyAssertion|
   #:|NegativeObjectPropertyAssertion|
   #:|DataPropertyAssertion|
   #:|NegativeDataPropertyAssertion|
   #:|Label|
   #:|Comment|
   #:|Annotation|
   #:|name|
   #:|kb|
   #:|OWL***-Literal|
   #:|OWLLiteral|
   #:|Literal|
   #:|Constant|
   #:|facet|
   #:|FacetRestriction|
   #:|length|
   #:|minLength|
   #:|maxLength|
   #:|pattern|
   #:|minInclusive|
   #:|maxInclusive|
   #:|minExclusive|
   #:|maxExclusive|
   #:|totalDigits|
   #:|fractionDigits|
   #:|DataExactCardinality|
   #:|Cardinality|
   #:|http://www.w3.org/2001/XMLSchema#positiveInteger|
   #:|http://www.w3.org/2001/XMLSchema#XMLLiteral|
   #:|http://www.w3.org/2001/XMLSchema#Literal|
   #:|http://www.w3.org/2001/XMLSchema#anyURI|
   #:|http://www.w3.org/2001/XMLSchema#base64binary|
   #:|http://www.w3.org/2001/XMLSchema#hexBinary|
   #:|http://www.w3.org/2001/XMLSchema#normalizedString|
   #:|http://www.w3.org/2001/XMLSchema#token|
   #:|http://www.w3.org/2001/XMLSchema#language|
   #:|http://www.w3.org/2001/XMLSchema#Name|
   #:|http://www.w3.org/2001/XMLSchema#NMTOKEN|
   #:|http://www.w3.org/2001/XMLSchema#NMTOKENS|
   #:|http://www.w3.org/2001/XMLSchema#NCName|
   #:|http://www.w3.org/2001/XMLSchema#ID|
   #:|http://www.w3.org/2001/XMLSchema#IDREF|
   #:|http://www.w3.org/2001/XMLSchema#IDREFS|
   #:|http://www.w3.org/2001/XMLSchema#ENTITY|
   #:|http://www.w3.org/2001/XMLSchema#ENTITIES|
   #:|http://www.w3.org/2001/XMLSchema#QName|
   #:|http://www.w3.org/2001/XMLSchema#date|
   #:|http://www.w3.org/2001/XMLSchema#time|
   #:|http://www.w3.org/2001/XMLSchema#dateTime|
   #:|http://www.w3.org/2001/XMLSchema#gYear|
   #:|http://www.w3.org/2001/XMLSchema#gYearMonth|
   #:|http://www.w3.org/2001/XMLSchema#gMonth|
   #:|http://www.w3.org/2001/XMLSchema#gMonthDay|
   #:|http://www.w3.org/2001/XMLSchema#gDay|
   #:|http://www.w3.org/2001/XMLSchema#duration|
   #:|http://www.w3.org/2001/XMLSchema#negativeInteger|
   #:|http://www.w3.org/2001/XMLSchema#nonNegativeInteger|
   #:|http://www.w3.org/2001/XMLSchema#nonPositiveInteger|
   #:|http://www.w3.org/2001/XMLSchema#integer|
   #:|http://www.w3.org/2001/XMLSchema#byte|
   #:|http://www.w3.org/2001/XMLSchema#unsignedByte|
   #:|http://www.w3.org/2001/XMLSchema#unsignedShort|
   #:|http://www.w3.org/2001/XMLSchema#unsignedInt|
   #:|http://www.w3.org/2001/XMLSchema#unsignedLong|
   #:|http://www.w3.org/2001/XMLSchema#short|
   #:|http://www.w3.org/2001/XMLSchema#int|
   #:|http://www.w3.org/2001/XMLSchema#long|
   #:|http://www.w3.org/2001/XMLSchema#float|
   #:|http://www.w3.org/2001/XMLSchema#double|
   #:|http://www.w3.org/2001/XMLSchema#decimal|
   #:|http://www.w3.org/2001/XMLSchema#boolean|
   #:|http://www.w3.org/2001/XMLSchema#string|
   #:|http://www.w3.org/2001/XMLSchema#maxExclusive|
   #:|http://www.w3.org/2001/XMLSchema#maxInclusive|
   #:|http://www.w3.org/2001/XMLSchema#minExclusive|
   #:|http://www.w3.org/2001/XMLSchema#minInclusive|
   #:|http://www.w3.org/2001/XMLSchema#minLength|
   #:|http://www.w3.org/2001/XMLSchema#maxLength|
   #:|http://www.w3.org/2001/XMLSchema#length|
   #:|http://www.w3.org/2001/XMLSchema#pattern|
   #:|http://www.w3.org/2001/XMLSchema#totalDigits|
   #:|http://www.w3.org/2001/XMLSchema#fractionDigits|
   #:|http://www.w3.org/2000/01/rdf-schema#comment|
   #:|http://www.w3.org/2000/01/rdf-schema#Comment|
   #:|http://www.w3.org/2000/01/rdf-schema#label|
   #:|http://www.w3.org/2000/01/rdf-schema#Label|
   #:|http://www.w3.org/2000/01/rdf-schema#seeAlso|
   #:|http://www.w3.org/2000/01/rdf-schema#SeeAlso|
   #:|http://www.w3.org/2002/07/owl#isDefinedBy|
   #:|http://www.w3.org/2002/07/owl#IsDefinedBy|
   #:|http://www.w3.org/2002/07/owl#versionInfo|
   #:|http://www.w3.org/2002/07/owl#VersionInfo|
   #:|http://www.w3.org/2002/07/owl#Thing|
   #:|http://www.w3.org/2002/07/owl#Nothing|
   #:|http://www.w3.org/2002/07/owl#topDataProperty|
   #:|http://www.w3.org/2002/07/owl#bottomDataProperty|
   #:|http://www.w3.org/2002/07/owl#topObjectProperty|
   #:|http://www.w3.org/2002/07/owl#bottomObjectProperty|
   #:d-filler
   #:d-literal
   #:d-all
   #:d-some
   #:d-at-least
   #:d-at-most
   #:d-exactly
   #:d-facet
   #:d-base-type
   #:d-complement
   #:d-and
   #:d-or
   #:d-datarange
   #:d-restriction
   #:d-possible-values
   #:nrql-warning
   #:nrql-error
   #:owlapi-kb
   #:with-reasoner
   #:last-answer
   #:last-error
   #:last-output-stream-string
   #:simple-output
   #:return-policy
   #:auto-mode
   #:auto-apply
   #:owllink2-eval-request
   #:get-minilisp-value
   #:racer-prepare-substrate
   #:retrieve-annotation-datatype-values
   #:count
   #:count-distinct
   #:sum
   #:sum-distinct
   #:substract
   #:substract-distinct
   #:prod
   #:prod-distinct
   #:div
   #:div-distinct
   #:avg
   #:minilisp
   #:max
   #:min
   #:asc
   #:desc
   #:all-types
   #:types
   #:instantiators
   #:all-instantiators
   #:all-types-flat
   #:all-instantiators-flat
   #:types-flat
   #:instantiators-flat
   #:direct-types
   #:most-specific-types
   #:most-specific-instantiators
   #:direct-instantiators
   #:direct-types-flat
   #:most-specific-types-flat
   #:most-specific-instantiators-flat
   #:direct-instantiators-flat
   #:individual-synonyms
   #:concept-synonyms
   #:describe
   #:nrql-equal-role
   #:bind-individual
   #:inv
   #:not
   #:neg
   #:and
   #:or
   #:one-of
   #:d-filler
   #:d-all
   #:d-some
   #:d-at-least
   #:d-at-most
   #:d-exactly
   #:d-facet
   #:d-literal
   #:d-base-type
   #:d-complement
   #:d-datarange
   #:d-possible-values
   #:new-ind
   #:group-by
   #:order
   #:strict
   #:tag
   #:satisfies
   #:top
   #:bottom
   #:true-query
   #:false-query
   #:constraint
   #:has-known-successor
   #:substitute
   #:insert
   #:same-as
   #:different-from
   #:equal
   #:=
   #:intersection
   #:union
   #:cap
   #:cup
   #:lambda
   #:told-value
   #:told-values
   #:told-value-if-exists
   #:told-values-if-exists
   #:datatype-filler
   #:datatype-fillers
   #:annotation-datatype-filler
   #:annotation-datatype-fillers
   #:unknown-operator
   #:bindings-from
   #:no-told-value
   #:no-known-cd-objects
   #:project
   #:project-to
   #:pi
   #:real-top
   #:real-bottom
   #:add-doc-phrase1
   #:add-doc-image-data1
   #:add-doc-image-data-from-file1
   #:add-doc-image-file1
   #:del-doc-entry1
   #:add-doc-entry1
   #:clear-all-documentation
   #:compute-abox-difference2
   #:compute-abox-difference1
   #:remove-implied-concept-assertions
   #:make-abduction-rule-from-aboxes
   #:make-backward-rule-from-aboxes
   #:make-forward-rule-from-aboxes
   #:make-query-from-abox
   #:create-subgraph-aboxes
   #:compute-subgraph-aboxes
   #:get-new-ind-prefix
   #:set-new-ind-prefix
   #:get-new-ind-counter
   #:set-new-ind-counter
   #:get-minimum
   #:get-maximum
   #:abox-entails-abox-p
   #:disable-abduction
   #:enable-abduction
   #:|OWLAPI-readOntology|
   #:|OWLAPI-saveOntology|
   #:|OWLAPI-writeXMLOntologyFile|
   #:|OWLAPI-writeFunctionalOntologyFile|
   #:|OWLAPI-writeOntologyFile|
   #:|OWLAPI-readXMLOntologyDocument|
   #:|OWLAPI-readXMLOntologyFile|
   #:|OWLAPI-readFunctionalOntologyDocument|
   #:|OWLAPI-readFunctionalOntologyFile|
   #:|OWLAPI-parseNative|
   #:|OWLAPI-parse|
   #:update-racer
   #:check-for-updates
   #:load-racer-plugins
   #:load-racer-patches
   #:installed-plugins
   #:installed-patches
   #:load-racer-plugin
   #:load-racer-patch
   #:make-plugin-from-fasl-file
   #:swrl-create-forward-chainging-rules
   #:swrl-create-abduction-rules-if-possible
   #:get-prefixes
   #:delete-prefix-mappings
   #:|OWLAPI-restoreImage|
   #:|OWLAPI-storeImage|
   #:owlapi-add-axiom
   #:owlapi-add-axioms
   #:owlapi-axiom-loaded?
   #:owlapi-axiom-to-id
   #:owlapi-id-to-axiom
   #:owlapi-remove-axiom
   #:owlapi-remove-axioms
   #:owlapi-set-ontology-uri
   #:owlapi-abort
   #:owlapi-add-prefix
   #:owlapi-advance-progress
   #:owlapi-apply-changes
   #:owlapi-auto-add-axioms-to
   #:owlapi-auto-apply-changes
   #:owlapi-auto-batch-add-axioms-to
   #:owlapi-auto-batch-remove-axioms-from
   #:owlapi-auto-remove-axioms-from
   #:owlapi-batch-synchronize
   #:owlapi-classify
   #:owlapi-clear-changes
   #:owlapi-clear-ontologies
   #:owlapi-clear-registry
   #:owlapi-consider-declarations
   #:owlapi-contains
   #:owlapi-describe-ontologies
   #:owlapi-describe-ontology
   #:owlapi-describe-reasoner
   #:owlapi-describe-reasoners
   #:owlapi-disable-auto-mode
   #:owlapi-disable-incremental-updates
   #:owlapi-disable-lookup-mode
   #:owlapi-disable-memory-saving-mode
   #:owlapi-disable-simplified-protocol
   #:owlapi-disable-transient-axiom-mode
   #:owlapi-dispose
   #:owlapi-dispose-axiom
   #:owlapi-dispose-axioms
   #:owlapi-dispose-ontologies
   #:owlapi-dispose-ontology
   #:owlapi-dispose-reasoner
   #:owlapi-dont-register-declared-entities
   #:owlapi-dont-register-referenced-entities
   #:owlapi-enable-incremental-updates
   #:owlapi-enable-lookup-mode
   #:owlapi-enable-memory-saving-mode
   #:owlapi-enable-simplified-protocol
   #:owlapi-enable-transient-axiom-mode
   #:owlapi-export-ontology
   #:owlapi-export-reasoner
   #:owlapi-find-id-from-object
   #:owlapi-find-object-from-id
   #:owlapi-get-all-ontologies
   #:owlapi-get-ancestor-classes
   #:owlapi-get-ancestor-properties
   #:owlapi-get-annotation-axioms-for-axiom
   #:owlapi-get-auto-declare-data-properties
   #:owlapi-get-auto-ontology
   #:owlapi-get-axiom-counter
   #:owlapi-get-axioms
   #:owlapi-get-axioms-in
   #:owlapi-get-axioms-of-type
   #:owlapi-get-axioms-of-type-in
   #:owlapi-get-axioms-per-ontology
   #:owlapi-get-changes
   #:owlapi-get-current-reasoner
   #:owlapi-get-data-property-relationships
   #:owlapi-get-data-property-values
   #:owlapi-get-descendant-classes
   #:owlapi-get-descendant-properties
   #:owlapi-get-different-individuals
   #:owlapi-get-disjoint-classes
   #:owlapi-get-disjoint-data-properties
   #:owlapi-get-disjoint-object-properties
   #:owlapi-get-domains
   #:owlapi-get-equivalent-classes
   #:owlapi-get-equivalent-properties
   #:owlapi-get-inconsistent-classes
   #:owlapi-get-individuals
   #:owlapi-get-instances
   #:owlapi-get-inverse-properties
   #:owlapi-get-loaded-ontologies
   #:owlapi-get-owl-annotation-assertion-axiom
   #:owlapi-get-owl-annotation-property-domain-axiom
   #:owlapi-get-owl-annotation-property-range-axiom
   #:owlapi-get-owl-asymmetric-object-property-axiom
   #:owlapi-get-owl-axiom-annotation-axiom
   #:owlapi-get-owl-class-assertion-axiom
   #:owlapi-get-owl-data-property-assertion-axiom
   #:owlapi-get-owl-data-property-domain-axiom
   #:owlapi-get-owl-data-property-range-axiom
   #:owlapi-get-owl-data-sub-property-axiom
   #:owlapi-get-owl-datatype-definition-axiom
   #:owlapi-get-owl-declaration-axiom
   #:owlapi-get-owl-different-individuals-axiom
   #:owlapi-get-owl-disjoint-classes-axiom
   #:owlapi-get-owl-disjoint-data-properties-axiom
   #:owlapi-get-owl-disjoint-object-properties-axiom
   #:owlapi-get-owl-disjoint-union-axiom
   #:owlapi-get-owl-entity-annotation-axiom
   #:owlapi-get-owl-equivalent-classes-axiom
   #:owlapi-get-owl-equivalent-data-properties-axiom
   #:owlapi-get-owl-equivalent-object-properties-axiom
   #:owlapi-get-owl-functional-data-property-axiom
   #:owlapi-get-owl-functional-object-property-axiom
   #:owlapi-get-owl-has-key-axiom
   #:owlapi-get-owl-implicit-declaration-axiom
   #:owlapi-get-owl-imports-declaration-axiom
   #:owlapi-get-owl-inverse-functional-object-property-axiom
   #:owlapi-get-owl-inverse-object-properties-axiom
   #:owlapi-get-owl-irreflexive-object-property-axiom
   #:owlapi-get-owl-negative-data-property-assertion-axiom
   #:owlapi-get-owl-negative-object-property-assertion-axiom
   #:owlapi-get-owl-object-property-assertion-axiom
   #:owlapi-get-owl-object-property-chain-sub-property-axiom
   #:owlapi-get-owl-object-property-domain-axiom
   #:owlapi-get-owl-object-property-range-axiom
   #:owlapi-get-owl-object-sub-property-axiom
   #:owlapi-get-owl-ontology-annotation-axiom
   #:owlapi-get-owl-ontology-version-declaration-axiom
   #:owlapi-get-owl-prefix-declaration-axiom
   #:owlapi-get-owl-really-implicit-declaration-axiom
   #:owlapi-get-owl-reflexive-object-property-axiom
   #:owlapi-get-owl-same-individuals-axiom
   #:owlapi-get-owl-sub-annotation-property-axiom
   #:owlapi-get-owl-sub-annotation-property-of-axiom
   #:owlapi-get-owl-sub-class-axiom
   #:owlapi-get-owl-symmetric-object-property-axiom
   #:owlapi-get-owl-transitive-object-property-axiom
   #:owlapi-get-object-property-relationships
   #:owlapi-get-object-property-values
   #:owlapi-get-ontologies
   #:owlapi-get-prefixes
   #:owlapi-get-ranges
   #:owlapi-get-reasoners
   #:owlapi-get-related-individuals
   #:owlapi-get-related-values
   #:owlapi-get-same-individuals
   #:owlapi-get-sub-classes
   #:owlapi-get-sub-properties
   #:owlapi-get-super-classes
   #:owlapi-get-super-properties
   #:owlapi-get-types
   #:owlapi-has-data-property-relationship
   #:owlapi-has-object-property-relationship
   #:owlapi-has-type
   #:owlapi-ignore-annotations
   #:owlapi-ignore-declarations
   #:owlapi-init
   #:owlapi-is-asymmetric
   #:owlapi-is-class
   #:owlapi-is-classified
   #:owlapi-is-consistent
   #:owlapi-is-defined-class
   #:owlapi-is-defined-data-property
   #:owlapi-is-defined-individual
   #:owlapi-is-defined-object-property
   #:owlapi-is-different-individual
   #:owlapi-is-entailed
   #:owlapi-is-equivalent-class
   #:owlapi-is-functional
   #:owlapi-is-inverse-functional
   #:owlapi-is-irreflexive
   #:owlapi-is-realised
   #:owlapi-is-reflexive
   #:owlapi-is-same-individual
   #:owlapi-is-satisfiable
   #:owlapi-is-sub-class-of
   #:owlapi-is-symmetric
   #:owlapi-is-transitive
   #:owlapi-keep-annotations
   #:owlapi-load-axiom
   #:owlapi-load-axioms
   #:owlapi-load-ontologies
   #:owlapi-load-ontology
   #:owlapi-manually-apply-changes
   #:owlapi-merge-ontologies
   #:owlapi-new-ontology
   #:owlapi-new-reasoner
   #:owlapi-new-reasoner1
   #:owlapi-next-axiom-use-id
   #:owlapi-parse
   #:owlapi-parse-native
   #:owlapi-read-functional-ontology-document
   #:owlapi-read-functional-ontology-file
   #:owlapi-read-ontology
   #:owlapi-read-xml-ontology-document
   #:owlapi-read-xml-ontology-file
   #:owlapi-realize
   #:owlapi-register-declared-entities
   #:owlapi-register-last-answer
   #:owlapi-register-object
   #:owlapi-register-referenced-entities
   #:owlapi-reload-loaded-ontologies
   #:owlapi-remove-prefix
   #:owlapi-reset-axiom-counter
   #:owlapi-restore-image
   #:owlapi-save-ontology
   #:owlapi-set-auto-declare-data-properties
   #:owlapi-set-axiom-counter
   #:owlapi-set-current-reasoner
   #:owlapi-set-progress
   #:owlapi-set-progress-range
   #:owlapi-set-return-policy
   #:owlapi-sleep
   #:owlapi-store-image
   #:owlapi-unload-axiom
   #:owlapi-unload-axioms
   #:owlapi-unload-ontologies
   #:owlapi-unload-ontology
   #:owlapi-uses-incremental-updates
   #:owlapi-uses-simplified-protocol
   #:owlapi-write-functional-ontology-file
   #:owlapi-write-ontology-file
   #:owlapi-write-xml-ontology-file
   #:|OWLAPI-exportReasoner|
   #:|OWLAPI-exportOntology|
   #:|OWLAPI-SetOntologyURI|
   #:|OWLAPI-RemoveAxioms|
   #:|OWLAPI-removeAxioms|
   #:|OWLAPI-RemoveAxiom|
   #:|OWLAPI-removeAxiom|
   #:|OWLAPI-AddAxioms|
   #:|OWLAPI-addAxioms|
   #:|OWLAPI-AddAxiom|
   #:|OWLAPI-addAxiom|
   #:|OWLAPI-applyChanges|
   #:|OWLAPI-manuallyApplyChanges|
   #:|OWLAPI-autoApplyChanges|
   #:|OWLAPI-getChanges|
   #:|OWLAPI-clearChanges|
   #:|OWLAPI-getOWLObjectPropertyRangeAxiom|
   #:|OWLAPI-getOWLDataPropertyRangeAxiom|
   #:|OWLAPI-getOWLObjectPropertyDomainAxiom|
   #:|OWLAPI-getOWLDataPropertyDomainAxiom|
   #:|OWLAPI-getOWLDataSubPropertyAxiom|
   #:|OWLAPI-getOWLObjectSubPropertyAxiom|
   #:|OWLAPI-getOWLTransitiveObjectPropertyAxiom|
   #:|OWLAPI-getOWLSymmetricObjectPropertyAxiom|
   #:|OWLAPI-getOWLReflexiveObjectPropertyAxiom|
   #:|OWLAPI-getOWLIrreflexiveObjectPropertyAxiom|
   #:|OWLAPI-getOWLInverseFunctionalObjectPropertyAxiom|
   #:|OWLAPI-getOWLAsymmetricObjectPropertyAxiom|
   #:|OWLAPI-getOWLObjectPropertyChainSubPropertyAxiom|
   #:|OWLAPI-getOWLInverseObjectPropertiesAxiom|
   #:|OWLAPI-getOWLEquivalentObjectPropertiesAxiom|
   #:|OWLAPI-getOWLEquivalentDataPropertiesAxiom|
   #:|OWLAPI-getOWLDisjointObjectPropertiesAxiom|
   #:|OWLAPI-getOWLDisjointDataPropertiesAxiom|
   #:|OWLAPI-getOWLFunctionalObjectPropertyAxiom|
   #:|OWLAPI-getOWLFunctionalDataPropertyAxiom|
   #:|OWLAPI-getOWLNegativeObjectPropertyAssertionAxiom|
   #:|OWLAPI-getOWLObjectPropertyAssertionAxiom|
   #:|OWLAPI-getOWLNegativeDataPropertyAssertionAxiom|
   #:|OWLAPI-getOWLDataPropertyAssertionAxiom|
   #:|OWLAPI-getOWLSameIndividualsAxiom|
   #:|OWLAPI-getOWLDifferentIndividualsAxiom|
   #:|OWLAPI-getOWLClassAssertionAxiom|
   #:|OWLAPI-getOWLSubClassAxiom|
   #:|OWLAPI-getOWLEquivalentClassesAxiom|
   #:|OWLAPI-getOWLDisjointUnionAxiom|
   #:|OWLAPI-getOWLDisjointClassesAxiom|
   #:|OWLAPI-getOWLPrefixDeclarationAxiom|
   #:|OWLAPI-getOWLOntologyVersionDeclarationAxiom|
   #:|OWLAPI-getOWLImportsDeclarationAxiom|
   #:|OWLAPI-getOWLReallyImplicitDeclarationAxiom|
   #:|OWLAPI-getOWLImplicitDeclarationAxiom|
   #:|OWLAPI-getOWLDeclarationAxiom|
   #:|OWLAPI-getOWLAnnotationPropertyRangeAxiom|
   #:|OWLAPI-getOWLAnnotationPropertyDomainAxiom|
   #:|OWLAPI-getOWLSubAnnotationPropertyAxiom|
   #:|OWLAPI-getOWLSubAnnotationPropertyOfAxiom|
   #:|OWLAPI-getOWLAnnotationAssertionAxiom|
   #:|OWLAPI-getOWLOntologyAnnotationAxiom|
   #:|OWLAPI-getOWLEntityAnnotationAxiom|
   #:|OWLAPI-getOWLAxiomAnnotationAxiom|
   #:|OWLAPI-getOWLHasKeyAxiom|
   #:|OWLAPI-getOWLDatatypeDefinitionAxiom|
   #:|OWLAPI-getPrefixes|
   #:|OWLAPI-removePrefix|
   #:|OWLAPI-addPrefix|
   #:|OWLAPI-getAnnotationAxiomsForAxiom|
   #:|OWLAPI-getAxiomsOfTypeIn|
   #:|OWLAPI-getAxiomsOfType|
   #:|OWLAPI-getAxiomsIn|
   #:|OWLAPI-getAxiomsPerOntology|
   #:|OWLAPI-getAxioms|
   #:|OWLAPI-AxiomLoaded?|
   #:|OWLAPI-AxiomToID|
   #:|OWLAPI-IDToAxiom|
   #:|OWLAPI-disposeAxioms|
   #:|OWLAPI-disposeAxiom|
   #:|OWLAPI-unloadAxioms|
   #:|OWLAPI-unloadAxiom|
   #:|OWLAPI-loadAxioms|
   #:|OWLAPI-loadAxiom|
   #:|OWLAPI-resetAxiomCounter|
   #:|OWLAPI-setAxiomCounter|
   #:|OWLAPI-getAxiomCounter|
   #:|OWLAPI-isSatisfiable|
   #:|OWLAPI-dispose|
   #:|OWLAPI-clearOntologies|
   #:|OWLAPI-unloadOntology|
   #:|OWLAPI-unloadOntologies|
   #:|OWLAPI-isDefinedIndividual|
   #:|OWLAPI-isDefinedDataProperty|
   #:|OWLAPI-isDefinedObjectProperty|
   #:|OWLAPI-isDefinedClass|
   #:|OWLAPI-realize|
   #:|OWLAPI-isRealised|
   #:|OWLAPI-classify|
   #:|OWLAPI-isClassified|
   #:|OWLAPI-considerDeclarations|
   #:|OWLAPI-ignoreDeclarations|
   #:|OWLAPI-keepAnnotations|
   #:|OWLAPI-ignoreAnnotations|
   #:|OWLAPI-disableMemorySavingMode|
   #:|OWLAPI-enableMemorySavingMode|
   #:|OWLAPI-batchSynchronize|
   #:|OWLAPI-isEntailed|
   #:|OWLAPI-disableTransientAxiomMode|
   #:|OWLAPI-enableTransientAxiomMode|
   #:|OWLAPI-disableLookupMode|
   #:|OWLAPI-enableLookupMode|
   #:|OWLAPI-disableAutoMode|
   #:|OWLAPI-autoBatchRemoveAxiomsFrom|
   #:|OWLAPI-autoRemoveAxiomsFrom|
   #:|OWLAPI-autoBatchAddAxiomsTo|
   #:|OWLAPI-autoAddAxiomsTo|
   #:|OWLAPI-getAutoOntology|
   #:|OWLAPI-getAutoDeclareDataProperties|
   #:|OWLAPI-setAutoDeclareDataProperties|
   #:|OWLAPI-reloadLoadedOntologies|
   #:|OWLAPI-disposeOntologies|
   #:|OWLAPI-loadOntologies|
   #:|OWLAPI-getAllOntologies|
   #:|OWLAPI-contains|
   #:|OWLAPI-getLoadedOntologies|
   #:|OWLAPI-getOntologies|
   #:|OWLAPI-loadOntology|
   #:|OWLAPI-disposeOntology|
   #:|OWLAPI-mergeOntologies|
   #:|OWLAPI-newOntology|
   #:|OWLAPI-describeOntologies|
   #:|OWLAPI-describeOntology|
   #:|OWLAPI-describeReasoners|
   #:|OWLAPI-describeReasoner|
   #:|OWLAPI-isAsymmetric|
   #:|OWLAPI-isIrreflexive|
   #:|OWLAPI-isReflexive|
   #:|OWLAPI-isTransitive|
   #:|OWLAPI-isSymmetric|
   #:|OWLAPI-isInverseFunctional|
   #:|OWLAPI-getInverseProperties|
   #:|OWLAPI-getDisjointDataProperties|
   #:|OWLAPI-getDisjointObjectProperties|
   #:|OWLAPI-getDisjointClasses|
   #:|OWLAPI-isFunctional|
   #:|OWLAPI-getRanges|
   #:|OWLAPI-getDomains|
   #:|OWLAPI-getEquivalentProperties|
   #:|OWLAPI-getDescendantProperties|
   #:|OWLAPI-getAncestorProperties|
   #:|OWLAPI-getSubProperties|
   #:|OWLAPI-getSuperProperties|
   #:|OWLAPI-getDifferentIndividuals|
   #:|OWLAPI-getDataPropertyValues|
   #:|OWLAPI-getObjectPropertyValues|
   #:|OWLAPI-getInstances|
   #:|OWLAPI-isDifferentIndividual|
   #:|OWLAPI-isSameIndividual|
   #:|OWLAPI-getSameIndividuals|
   #:|OWLAPI-getRelatedValues|
   #:|OWLAPI-getRelatedIndividuals|
   #:|OWLAPI-hasDataPropertyRelationship|
   #:|OWLAPI-hasObjectPropertyRelationship|
   #:|OWLAPI-hasType|
   #:|OWLAPI-getDataPropertyRelationships|
   #:|OWLAPI-getObjectPropertyRelationships|
   #:|OWLAPI-getIndividuals|
   #:|OWLAPI-getTypes|
   #:|OWLAPI-isConsistent|
   #:|OWLAPI-getInconsistentClasses|
   #:|OWLAPI-getEquivalentClasses|
   #:|OWLAPI-getDescendantClasses|
   #:|OWLAPI-getSubClasses|
   #:|OWLAPI-getAncestorClasses|
   #:|OWLAPI-getSuperClasses|
   #:|OWLAPI-isEquivalentClass|
   #:|OWLAPI-isSubClassOf|
   #:|OWLAPI-isClass|
   #:|OWLAPI-findIDFromObject|
   #:|OWLAPI-findObjectFromID|
   #:|OWLAPI-registerObject|
   #:|OWLAPI-registerLastAnswer|
   #:|OWLAPI-clearRegistry|
   #:|OWLAPI-setReturnPolicy|
   #:|OWLAPI-nextAxiomUseID|
   #:|OWLAPI-dontRegisterDeclaredEntities|
   #:|OWLAPI-registerDeclaredEntities|
   #:|OWLAPI-dontRegisterReferencedEntities|
   #:|OWLAPI-registerReferencedEntities|
   #:|OWLAPI-usesIncrementalUpdates|
   #:|OWLAPI-disableIncrementalUpdates|
   #:|OWLAPI-enableIncrementalUpdates|
   #:|OWLAPI-usesSimplifiedProtocol|
   #:|OWLAPI-disableSimplifiedProtocol|
   #:|OWLAPI-enableSimplifiedProtocol|
   #:|OWLAPI-advanceProgress|
   #:|OWLAPI-setProgress|
   #:|OWLAPI-setProgressRange|
   #:|OWLAPI-init|
   #:|OWLAPI-abort|
   #:|OWLAPI-sleep|
   #:|OWLAPI-getReasoners|
   #:|OWLAPI-getCurrentReasoner|
   #:|OWLAPI-setCurrentReasoner|
   #:|OWLAPI-disposeReasoner|
   #:|OWLAPI-newReasoner|
   #:|OWLAPI-newReasoner1|
   #:get-agraph-version
   #:get-nrql-version
   #:restore-server-image
   #:store-server-image
   #:restore-all-substrates
   #:restore-substrate
   #:store-all-substrates
   #:store-substrate-for-abox
   #:check-nrql-subscriptions
   #:disable-rcc-substrate-mirroring
   #:enable-rcc-substrate-mirroring
   #:del-rcc-edge1
   #:del-rcc-node1
   #:rcc-edge-description1
   #:rcc-node-description1
   #:rcc-edge-label1
   #:rcc-node-label1
   #:rcc-edge1
   #:rcc-node1
   #:rcc-related1
   #:rcc-instance1
   #:delete-rcc-synonyms
   #:register-rcc-synonym
   #:rcc-consistent-p
   #:create-rcc-edge
   #:create-rcc-node
   #:set-rcc-box
   #:set-mirror-data-box
   #:get-edge-label-for-non-existent-edges
   #:set-edge-label-for-non-existent-edges
   #:description-implies-p
   #:edge-description1
   #:node-description1
   #:edge-label1
   #:node-label1
   #:del-data-edge1
   #:del-data-node1
   #:data-edge1
   #:data-node1
   #:set-data-box
   #:get-data-edge-description
   #:get-data-edge-label
   #:get-data-node-description
   #:get-data-node-label
   #:delete-data-edge
   #:delete-data-node
   #:create-data-edge
   #:create-data-node
   #:describe-all-edges
   #:get-substrate-edges
   #:describe-all-nodes
   #:get-substrate-nodes
   #:describe-all-substrates
   #:describe-substrate
   #:rmi
   #:get-proxy-server
   #:set-proxy-server
   #:check-ontology
   #:check-concept-coherence
   #:restore-standard-settings
   #:set-nrql-mode
   #:disable-query-realization
   #:enable-query-realization
   #:disable-query-repository
   #:enable-query-repository
   #:dont-report-inconsistent-queries-and-rules
   #:report-inconsistent-queries-and-rules
   #:describe-query-processing-mode
   #:describe-current-substrate
   #:get-process-pool-size
   #:get-maximum-size-of-process-pool
   #:get-initial-size-of-process-pool
   #:set-maximum-size-of-process-pool
   #:set-initial-size-of-process-pool
   #:set-rewrite-defined-concepts
   #:optimizer-dont-ensure-late-lambda-evaluation
   #:optimizer-ensure-late-lambda-evaluation
   #:optimizer-dont-use-cardinality-heuristics
   #:optimizer-use-cardinality-heuristics
   #:optimizer-get-time-bound
   #:optimizer-set-time-bound
   #:optimizer-get-no-of-plans-upper-bound
   #:optimizer-set-no-of-plans-upper-bound
   #:disable-query-optimization
   #:enable-query-optimization
   #:include-permutations
   #:exclude-permutations
   #:dont-add-rule-consequences-automatically
   #:add-rule-consequences-automatically
   #:process-set-at-a-time
   #:process-tuple-at-a-time
   #:get-max-no-of-tuples-bound
   #:set-max-no-of-tuples-bound
   #:dont-check-abox-consistency-before-querying
   #:check-abox-consistency-before-querying
   #:enable-lazy-tuple-computation
   #:enable-eager-tuple-computation
   #:dont-add-role-assertions-for-datatype-properties
   #:add-role-assertions-for-datatype-properties
   #:disable-told-information-querying
   #:enable-told-information-querying
   #:disable-nrql-warnings
   #:enable-nrql-warnings
   #:disable-kb-has-changed-warning-tokens
   #:enable-kb-has-changed-warning-tokens
   #:disable-phase-two-starts-warning-tokens
   #:enable-phase-two-starts-warning-tokens
   #:disable-two-phase-query-processing-mode
   #:enable-two-phase-query-processing-mode
   #:enable-very-smart-abox-mirroring
   #:enable-smart-abox-mirroring
   #:disable-abox-mirroring
   #:enable-abox-mirroring
   #:dont-use-injective-variables-by-default
   #:use-injective-variables-by-default
   #:dont-use-individual-synonym-equivalence-classes
   #:use-individual-synonym-equivalence-classes
   #:dont-add-missing-top-conjuncts
   #:add-missing-top-conjuncts
   #:disable-data-substrate-mirroring
   #:enable-data-substrate-mirroring
   #:wait-for-rules-to-terminate
   #:wait-for-queries-to-terminate
   #:get-all-answers
   #:execute-or-reexecute-all-rules
   #:run-all-rules
   #:reexecute-all-rules
   #:execute-all-rules
   #:execute-or-reexecute-all-queries
   #:reexecute-all-queries
   #:run-all-queries
   #:execute-all-queries
   #:abort-all-rules
   #:abort-all-queries
   #:describe-all-definitions
   #:describe-definition
   #:delete-all-definitions
   #:activate-defined-query
   #:deactivate-defined-query
   #:dont-keep-defined-query-atoms
   #:keep-defined-query-atoms
   #:enable-lazy-unfolding-of-defined-queries
   #:disable-lazy-unfolding-of-defined-queries
   #:enable-defined-queries
   #:disable-defined-queries
   #:dont-prefer-defined-queries
   #:prefer-defined-queries
   #:dont-allow-overloaded-definitions
   #:allow-overloaded-definitions
   #:undefine-query
   #:define-and-prepare-query
   #:define-and-execute-query
   #:define-query
   #:inaccurate-rules
   #:accurate-rules
   #:inaccurate-queries
   #:accurate-queries
   #:sleeping-expensive-rules
   #:sleeping-cheap-rules
   #:waiting-expensive-rules
   #:waiting-cheap-rules
   #:sleeping-expensive-queries
   #:sleeping-cheap-queries
   #:waiting-expensive-queries
   #:waiting-cheap-queries
   #:running-expensive-rules
   #:running-cheap-rules
   #:running-expensive-queries
   #:running-cheap-queries
   #:expensive-rules
   #:cheap-rules
   #:expensive-queries
   #:cheap-queries
   #:terminated-rules
   #:processed-rules
   #:terminated-queries
   #:processed-queries
   #:sleeping-rules
   #:waiting-rules
   #:sleeping-queries
   #:waiting-queries
   #:running-rules
   #:running-queries
   #:active-rules
   #:active-queries
   #:prepared-rules
   #:ready-rules
   #:prepared-queries
   #:ready-queries
   #:answer-tbox-query1
   #:answer-tbox-query
   #:racer-answer-tbox-query1
   #:racer-answer-tbox-query
   #:racer-prepare-tbox-query1
   #:racer-prepare-tbox-query
   #:move-rules
   #:copy-rules
   #:apply-rule-under-premise1
   #:apply-rule-under-premise
   #:apply-rule
   #:racer-apply-rule-under-premise1
   #:racer-apply-rule1
   #:racer-apply-rule-under-premise
   #:racer-apply-rule
   #:prepare-rule1
   #:prepare-rule
   #:racer-prepare-rule1
   #:racer-prepare-rule
   #:answer-query-under-premise1
   #:answer-query-under-premise
   #:racer-answer-query-under-premise1
   #:racer-answer-query-under-premise
   #:answer-query1
   #:answer-query
   #:racer-answer-query1
   #:racer-answer-query
   #:get-answer-size
   #:prepare-query1
   #:prepare-query
   #:racer-prepare-query1
   #:racer-prepare-query
   #:delete-all-rules
   #:delete-all-queries
   #:describe-all-rules
   #:describe-all-queries
   #:all-rules
   #:all-queries
   #:all-different-from-assertions
   #:all-same-as-assertions
   #:get-abox-graph
   #:get-role-hierarchy
   #:get-concept-properties
   #:get-individual-annotation-fillers
   #:get-individual-annotation-datatype-fillers
   #:get-individual-datatype-fillers
   #:get-individual-successors
   #:prepare-nrql-engine
   #:in-unsafe-mode?
   #:exit-server
   #:full-reset
   #:reset-nrql-engine
   #:all-substrates
   #:delete-all-substrates
   #:get-substrate-type
   #:set-substrate-type
   #:reset-all-substrates
   #:server-value
   #:get-all-server-values
   #:get-all-values
   #:unbind-all
   #:unbind1
   #:defpar1
   #:defcon1
   #:server-function
   #:get-all-server-functions
   #:get-all-functions
   #:fcall
   #:undefine-all
   #:undefine1
   #:define1
   #:evaluate1
   #:set-racer-parameter
   #:add-explanation-assertions
   #:get-explanations
   #:get-number-of-explanations
   #:query-subscribers
   #:unsubscribe-from
   #:subscribe-to
   #:get-nodes-in-qbox-for-abox
   #:get-dag-of-qbox-for-abox
   #:show-qbox-for-abox
   #:query-equivalents
   #:query-descendants
   #:query-children
   #:query-ancestors
   #:query-parents
   #:query-equivalent-p
   #:query-entails-p
   #:classify-query
   #:rule-consistent-p
   #:query-consistent-p
   #:add-chosen-sets-of-rule-consequences
   #:get-chosen-sets-of-rule-consequences
   #:choose-current-set-of-rule-consequences
   #:execute-applicable-rules
   #:unapplicable-rules
   #:applicable-rules
   #:rule-unapplicable-p
   #:rule-applicable-p
   #:execute-or-reexecute-rule
   #:execute-or-reexecute-query
   #:reexecute-rule
   #:reexecute-query
   #:reprepare-rule
   #:reprepare-query
   #:rule-accurate-p
   #:query-accurate-p
   #:expensive-rule-p
   #:expensive-query-p
   #:cheap-rule-p
   #:cheap-query-p
   #:rule-terminated-p
   #:query-terminated-p
   #:rule-processed-p
   #:query-processed-p
   #:rule-sleeping-p
   #:query-sleeping-p
   #:rule-waiting-p
   #:query-waiting-p
   #:rule-running-p
   #:query-running-p
   #:rule-active-p
   #:query-active-p
   #:rule-prepared-p
   #:query-prepared-p
   #:rule-ready-p
   #:query-ready-p
   #:execute-rule
   #:get-all-remaining-sets-of-rule-consequences
   #:get-next-n-remaining-sets-of-rule-consequences
   #:get-next-set-of-rule-consequences
   #:next-set-of-rule-consequences-available-p
   #:get-current-set-of-rule-consequences
   #:get-all-remaining-tuples
   #:get-next-n-remaining-tuples
   #:get-next-tuple
   #:next-tuple-available-p
   #:get-current-tuple
   #:get-answer
   #:abort-rule
   #:abort-query
   #:execute-query
   #:delete-rule
   #:delete-query
   #:original-rule-antecedence
   #:original-query-body
   #:rule-antecedence
   #:query-body
   #:original-rule-consequence
   #:original-query-head
   #:rule-consequence
   #:query-head
   #:describe-rule
   #:describe-query
   #:describe-rule-status
   #:describe-query-status
   #:add-doc-phrase
   #:add-doc-image-data
   #:add-doc-image-data-from-file
   #:add-doc-image-file
   #:del-doc-entry
   #:add-doc-entry
   #:compute-abox-difference-alternative
   #:compute-abox-difference
   #:retrieve-with-explanation
   #:del-rcc-edge
   #:del-rcc-node
   #:rcc-edge-description
   #:rcc-node-description
   #:rcc-edge-label
   #:rcc-node-label
   #:rcc-edge
   #:rcc-node
   #:rcc-related
   #:rcc-instance
   #:rcc-synonym
   #:rcc-consistent?
   #:in-rcc-box
   #:in-mirror-data-box
   #:description-implies?
   #:edge-description
   #:node-description
   #:edge-label
   #:node-label
   #:del-data-edge
   #:del-data-node
   #:data-edge
   #:data-node
   #:in-data-box
   #:undefquery
   #:def-and-exec-query
   #:def-and-prep-query
   #:defquery
   #:tbox-retrieve1
   #:tbox-retrieve
   #:prepare-tbox-query1
   #:prepare-tbox-query
   #:firerule-under-premise1
   #:firerule-under-premise
   #:firerule1
   #:firerule
   #:apply-abox-rule-under-premise1
   #:apply-abox-rule-under-premise
   #:apply-abox-rule1
   #:apply-abox-rule
   #:preprule1
   #:preprule
   #:prepare-abox-rule1
   #:prepare-abox-rule
   #:retrieve-under-premise1
   #:retrieve-under-premise
   #:retrieve1
   #:retrieve
   #:prepare-abox-query1
   #:prepare-abox-query
   #:unbind
   #:defpar
   #:defcon
   #:undefine
   #:define
   #:evaluate
   #:with-future-bindings-evaluated
   #:with-future-bindings
   #:with-bindings-evaluated
   #:with-bindings
   #:with-nrql-settings-evaluated
   #:with-nrql-settings
   ))

(#+(or :sbcl :ccl) defparameter #-(or :sbcl :ccl) defconstant +nrql-symbols+ 
   '(
     #:IRI
     #:with-nrql-standard-settings
     #:racer-retrieve-individual-filled-roles
     #:racer-retrieve-individual-fillers
     #:racer-retrieve-related-individuals
     #:racer-dummy-substrate
     #:data-substrate
     #:mirror-data-substrate
     #:mirror-sql-data-substrate
     #:rcc-substrate
     #:rcc-mirror-substrate
     #:master-top-query
     #:master-bottom-query
     #:top-query
     #:bottom-query
     #:top-role
     #:bottom-role
     #:defer
     #:xml-output
     #:xml-input
     #:xml-native-output
     #:sequence
     #:answer-sequence
     #:quiet-sequence
     #:owlapi-sequence
     #:owlapi-test-sequence
     #:owlapi-answer-sequence
     #:owlapi-quiet-sequence
     #:|OWLAPI-sequence|
     #:|OWLAPI-testSequence|
     #:|OWLAPI-answerSequence|
     #:|OWLAPI-quietSequence|
     #:|OWLAPI-getLastAnswer|
     #:|OWLAPI-getIDsOfLastAnswer|
     #:|OWLAPI-getLastOutputStreamString|
     #:lisp-to-xml
     #:xml-to-lisp
     #:nrql-equal-role
     #:taxonomy-node
     #:has-synonym
     #:has-child
     #:has-parent
     #:has-descendant
     #:has-ancestor
     #:count
     #:sum
     #:prod
     #:avg
     #:substract
     #:div
     #:minilisp
     #:minilisp-server-function-p
     #:minilisp-server-value-p
     #:|OWLAxiom|
     #:|OWLLogicalAxiom|
     #:|OWLOntologyURIAttributeAxiom|
     #:|OWLAxiomWithEntitySlotAxiom|
     #:|OWLHasKeyAxiom|
     #:|OWLDatatypeDefinitionAxiom|
     #:|OWLPropertyAxiom|
     #:|OWLIndividualAxiom|
     #:|OWLClassAxiom|
     #:|OWLNaryDataPropertyAxiom|
     #:|OWLNaryObjectPropertyAxiom|
     #:|OWLDataPropertyAxiom|
     #:|OWLObjectPropertyAxiom|
     #:|OWLEquivalentDataPropertiesAxiom|
     #:|OWLDisjointDataPropertiesAxiom|
     #:|OWLInverseObjectPropertiesAxiom|
     #:|OWLEquivalentObjectPropertiesAxiom|
     #:|OWLDisjointObjectPropertiesAxiom|
     #:|OWLDataPropertyRangeAxiom|
     #:|OWLDataPropertyDomainAxiom|
     #:|OWLDataSubPropertyAxiom|
     #:|OWLFunctionalDataPropertyAxiom|
     #:|OWLObjectPropertyRangeAxiom|
     #:|OWLObjectPropertyDomainAxiom|
     #:|OWLObjectSubPropertyAxiom|
     #:|OWLTransitiveObjectPropertyAxiom|
     #:|OWLSymmetricObjectPropertyAxiom|
     #:|OWLReflexiveObjectPropertyAxiom|
     #:|OWLIrreflexiveObjectPropertyAxiom|
     #:|OWLInverseFunctionalObjectPropertyAxiom|
     #:|OWLAsymmetricObjectPropertyAxiom|
     #:|OWLAntiSymmetricObjectPropertyAxiom|
     #:|OWLObjectPropertyChainSubPropertyAxiom|
     #:|OWLFunctionalObjectPropertyAxiom|
     #:|OWLIndividualRelationshipAxiom|
     #:|OWLClassAssertionAxiom|
     #:|OWLNaryIndividualAxiom|
     #:|OWLObjectPropertyAssertionAxiom|
     #:|OWLDataPropertyAssertionAxiom|
     #:|OWLNegativeObjectPropertyAssertionAxiom|
     #:|OWLNegativeDataPropertyAssertionAxiom|
     #:|OWLSameIndividualsAxiom|
     #:|OWLDifferentIndividualsAxiom|
     #:|OWLNaryClassAxiom|
     #:|OWLSubClassAxiom|
     #:|OWLEquivalentClassesAxiom|
     #:|OWLDisjointUnionAxiom|
     #:|OWLDisjointClassesAxiom|
     #:|OWLPrefixDeclarationAxiom|
     #:|OWLOntologyVersionDeclarationAxiom|
     #:|OWLImportsDeclarationAxiom|
     #:|OWLDeclarationAxiom|
     #:|OWLAnnotationAxiom|
     #:|OWLImplicitDeclarationAxiom|
     #:|OWLAnnotationPropertyRangeAxiom|
     #:|OWLAnnotationPropertyDomainAxiom|
     #:|OWLSubAnnotationPropertyOfAxiom|
     #:|OWLAnnotationAssertionAxiom|
     #:|OWLOntologyAnnotationAxiom|
     #:|OWLEntityAnnotationAxiom|
     #:|OWLAxiomAnnotationAxiom|
     #:|SetOntologyURI|
     #:|OWLAxiomChange|
     #:|RemoveAxiom|
     #:|AddAxiom|
     #:|Reasoner|
     #:|WithReasoner|
     #:|Import|
     #:|Namespace|
     #:|Prefix|
     #:|Declaration|
     #:|Datatype|
     #:|OWLClass|
     #:|Class|
     #:|ObjectProperty|
     #:|DataProperty|
     #:|AnnotationProperty|
     #:|SubAnnotationPropertyOf|
     #:|AnnotationPropertyDomain|
     #:|AnnotationPropertyRange|
     #:|InverseObjectProperty|
     #:|ObjectInverseOf|
     #:|Individual|
     #:|NamedIndividual|
     #:|AnonymousIndividual|
     #:|Ontology|
     #:|Facet|
     #:|owl.Class|
     #:|owl.NamedIndividual|
     #:|owl.AnonymousIndividual|
     #:|owl.ObjectProperty|
     #:|owl.DataProperty|
     #:|owl.AnnotationProperty|
     #:|DataOneOf|
     #:|DataComplementOf|
     #:|DataIntersectionOf|
     #:|DataUnionOf|
     #:|DatatypeRestriction|
     #:|EntityAnnotation|
     #:|AnnotationAssertion|
     #:|ObjectUnionOf|
     #:|ObjectIntersectionOf|
     #:|ObjectComplementOf|
     #:|ObjectOneOf|
     #:|ObjectAllValuesFrom|
     #:|ObjectSomeValuesFrom|
     #:|ObjectExistsSelf|
     #:|ObjectHasSelf|
     #:|ObjectHasValue|
     #:|ObjectMaxCardinality|
     #:|ObjectMinCardinality|
     #:|ObjectExactCardinality|
     #:|DataAllValuesFrom|
     #:|DataSomeValuesFrom|
     #:|DataHasValue|
     #:|DataMaxCardinality|
     #:|DataMinCardinality|
     #:|EquivalentClasses|
     #:|DisjointClasses|
     #:|DisjointUnion|
     #:|SubObjectPropertyChain|
     #:|ObjectPropertyChain|
     #:|SubObjectPropertyOf|
     #:|EquivalentObjectProperties|
     #:|DisjointObjectProperties|
     #:|ObjectPropertyDomain|
     #:|ObjectPropertyRange|
     #:|InverseObjectProperties|
     #:|FunctionalObjectProperty|
     #:|InverseFunctionalObjectProperty|
     #:|ReflexiveObjectProperty|
     #:|IrreflexiveObjectProperty|
     #:|SymmetricObjectProperty|
     #:|AsymmetricObjectProperty|
     #:|TransitiveObjectProperty|
     #:|SubDataPropertyOf|
     #:|EquivalentDataProperties|
     #:|DisjointDataProperties|
     #:|DataPropertyDomain|
     #:|DataPropertyRange|
     #:|FunctionalDataProperty|
     #:|HasKey|
     #:|DatatypeDefinition|
     #:|SameIndividual|
     #:|SameIndividuals|
     #:|DifferentIndividual|
     #:|DifferentIndividuals|
     #:|ClassAssertion|
     #:|SubClassOf|
     #:|ObjectPropertyAssertion|
     #:|NegativeObjectPropertyAssertion|
     #:|DataPropertyAssertion|
     #:|NegativeDataPropertyAssertion|
     #:|Label|
     #:|Comment|
     #:|Annotation|
     #:|name|
     #:|kb|
     #:|OWL***-Literal|
     #:|OWLLiteral|
     #:|Literal|
     #:|Constant|
     #:|facet|
     #:|FacetRestriction|
     #:|length|
     #:|minLength|
     #:|maxLength|
     #:|pattern|
     #:|minInclusive|
     #:|maxInclusive|
     #:|minExclusive|
     #:|maxExclusive|
     #:|totalDigits|
     #:|fractionDigits|
     #:|DataExactCardinality|
     #:|Cardinality|
     #:|http://www.w3.org/2001/XMLSchema#positiveInteger|
     #:|http://www.w3.org/2001/XMLSchema#XMLLiteral|
     #:|http://www.w3.org/2001/XMLSchema#Literal|
     #:|http://www.w3.org/2001/XMLSchema#anyURI|
     #:|http://www.w3.org/2001/XMLSchema#base64binary|
     #:|http://www.w3.org/2001/XMLSchema#hexBinary|
     #:|http://www.w3.org/2001/XMLSchema#normalizedString|
     #:|http://www.w3.org/2001/XMLSchema#token|
     #:|http://www.w3.org/2001/XMLSchema#language|
     #:|http://www.w3.org/2001/XMLSchema#Name|
     #:|http://www.w3.org/2001/XMLSchema#NMTOKEN|
     #:|http://www.w3.org/2001/XMLSchema#NMTOKENS|
     #:|http://www.w3.org/2001/XMLSchema#NCName|
     #:|http://www.w3.org/2001/XMLSchema#ID|
     #:|http://www.w3.org/2001/XMLSchema#IDREF|
     #:|http://www.w3.org/2001/XMLSchema#IDREFS|
     #:|http://www.w3.org/2001/XMLSchema#ENTITY|
     #:|http://www.w3.org/2001/XMLSchema#ENTITIES|
     #:|http://www.w3.org/2001/XMLSchema#QName|
     #:|http://www.w3.org/2001/XMLSchema#date|
     #:|http://www.w3.org/2001/XMLSchema#time|
     #:|http://www.w3.org/2001/XMLSchema#dateTime|
     #:|http://www.w3.org/2001/XMLSchema#gYear|
     #:|http://www.w3.org/2001/XMLSchema#gYearMonth|
     #:|http://www.w3.org/2001/XMLSchema#gMonth|
     #:|http://www.w3.org/2001/XMLSchema#gMonthDay|
     #:|http://www.w3.org/2001/XMLSchema#gDay|
     #:|http://www.w3.org/2001/XMLSchema#duration|
     #:|http://www.w3.org/2001/XMLSchema#negativeInteger|
     #:|http://www.w3.org/2001/XMLSchema#nonNegativeInteger|
     #:|http://www.w3.org/2001/XMLSchema#nonPositiveInteger|
     #:|http://www.w3.org/2001/XMLSchema#integer|
     #:|http://www.w3.org/2001/XMLSchema#byte|
     #:|http://www.w3.org/2001/XMLSchema#unsignedByte|
     #:|http://www.w3.org/2001/XMLSchema#unsignedShort|
     #:|http://www.w3.org/2001/XMLSchema#unsignedInt|
     #:|http://www.w3.org/2001/XMLSchema#unsignedLong|
     #:|http://www.w3.org/2001/XMLSchema#short|
     #:|http://www.w3.org/2001/XMLSchema#int|
     #:|http://www.w3.org/2001/XMLSchema#long|
     #:|http://www.w3.org/2001/XMLSchema#float|
     #:|http://www.w3.org/2001/XMLSchema#double|
     #:|http://www.w3.org/2001/XMLSchema#decimal|
     #:|http://www.w3.org/2001/XMLSchema#boolean|
     #:|http://www.w3.org/2001/XMLSchema#string|
     #:|http://www.w3.org/2001/XMLSchema#maxExclusive|
     #:|http://www.w3.org/2001/XMLSchema#maxInclusive|
     #:|http://www.w3.org/2001/XMLSchema#minExclusive|
     #:|http://www.w3.org/2001/XMLSchema#minInclusive|
     #:|http://www.w3.org/2001/XMLSchema#minLength|
     #:|http://www.w3.org/2001/XMLSchema#maxLength|
     #:|http://www.w3.org/2001/XMLSchema#length|
     #:|http://www.w3.org/2001/XMLSchema#pattern|
     #:|http://www.w3.org/2001/XMLSchema#totalDigits|
     #:|http://www.w3.org/2001/XMLSchema#fractionDigits|
     #:|http://www.w3.org/2000/01/rdf-schema#comment|
     #:|http://www.w3.org/2000/01/rdf-schema#Comment|
     #:|http://www.w3.org/2000/01/rdf-schema#label|
     #:|http://www.w3.org/2000/01/rdf-schema#Label|
     #:|http://www.w3.org/2000/01/rdf-schema#seeAlso|
     #:|http://www.w3.org/2000/01/rdf-schema#SeeAlso|
     #:|http://www.w3.org/2002/07/owl#isDefinedBy|
     #:|http://www.w3.org/2002/07/owl#IsDefinedBy|
     #:|http://www.w3.org/2002/07/owl#versionInfo|
     #:|http://www.w3.org/2002/07/owl#VersionInfo|
     #:|http://www.w3.org/2002/07/owl#Thing|
     #:|http://www.w3.org/2002/07/owl#Nothing|
     #:|http://www.w3.org/2002/07/owl#topDataProperty|
     #:|http://www.w3.org/2002/07/owl#bottomDataProperty|
     #:|http://www.w3.org/2002/07/owl#topObjectProperty|
     #:|http://www.w3.org/2002/07/owl#bottomObjectProperty|
     #:d-filler
     #:d-literal
     #:d-all
     #:d-some
     #:d-at-least
     #:d-at-most
     #:d-exactly
     #:d-facet
     #:d-base-type
     #:d-complement
     #:d-and
     #:d-or
     #:d-datarange
     #:d-restriction
     #:d-possible-values
     #:nrql-warning
     #:nrql-error
     #:owlapi-kb
     #:with-reasoner
     #:last-answer
     #:last-error
     #:last-output-stream-string
     #:simple-output
     #:return-policy
     #:auto-mode
     #:auto-apply
     #:owllink2-eval-request
     #:get-minilisp-value
     #:racer-prepare-substrate
     #:retrieve-annotation-datatype-values
     #:count
     #:count-distinct
     #:sum
     #:sum-distinct
     #:substract
     #:substract-distinct
     #:prod
     #:prod-distinct
     #:div
     #:div-distinct
     #:avg
     #:minilisp
     #:max
     #:min
     #:asc
     #:desc
     #:all-types
     #:types
     #:instantiators
     #:all-instantiators
     #:all-types-flat
     #:all-instantiators-flat
     #:types-flat
     #:instantiators-flat
     #:direct-types
     #:most-specific-types
     #:most-specific-instantiators
     #:direct-instantiators
     #:direct-types-flat
     #:most-specific-types-flat
     #:most-specific-instantiators-flat
     #:direct-instantiators-flat
     #:individual-synonyms
     #:concept-synonyms
     #:describe
     #:nrql-equal-role
     #:bind-individual
     #:inv
     #:not
     #:neg
     #:and
     #:or
     #:one-of
     #:d-filler
     #:d-all
     #:d-some
     #:d-at-least
     #:d-at-most
     #:d-exactly
     #:d-facet
     #:d-literal
     #:d-base-type
     #:d-complement
     #:d-datarange
     #:d-possible-values
     #:new-ind
     #:group-by
     #:order
     #:strict
     #:tag
     #:satisfies
     #:top
     #:bottom
     #:true-query
     #:false-query
     #:constraint
     #:has-known-successor
     #:substitute
     #:insert
     #:same-as
     #:different-from
     #:equal
     #:=
     #:intersection
     #:union
     #:cap
     #:cup
     #:lambda
     #:told-value
     #:told-values
     #:told-value-if-exists
     #:told-values-if-exists
     #:datatype-filler
     #:datatype-fillers
     #:annotation-datatype-filler
     #:annotation-datatype-fillers
     #:unknown-operator
     #:bindings-from
     #:no-told-value
     #:no-known-cd-objects
     #:project
     #:project-to
     #:pi
     #:real-top
     #:real-bottom
     #:add-doc-phrase1
     #:add-doc-image-data1
     #:add-doc-image-data-from-file1
     #:add-doc-image-file1
     #:del-doc-entry1
     #:add-doc-entry1
     #:clear-all-documentation
     #:compute-abox-difference2
     #:compute-abox-difference1
     #:remove-implied-concept-assertions
     #:make-abduction-rule-from-aboxes
     #:make-backward-rule-from-aboxes
     #:make-forward-rule-from-aboxes
     #:make-query-from-abox
     #:create-subgraph-aboxes
     #:compute-subgraph-aboxes
     #:get-new-ind-prefix
     #:set-new-ind-prefix
     #:get-new-ind-counter
     #:set-new-ind-counter
     #:get-minimum
     #:get-maximum
     #:abox-entails-abox-p
     #:disable-abduction
     #:enable-abduction
     #:|OWLAPI-readOntology|
     #:|OWLAPI-saveOntology|
     #:|OWLAPI-writeXMLOntologyFile|
     #:|OWLAPI-writeFunctionalOntologyFile|
     #:|OWLAPI-writeOntologyFile|
     #:|OWLAPI-readXMLOntologyDocument|
     #:|OWLAPI-readXMLOntologyFile|
     #:|OWLAPI-readFunctionalOntologyDocument|
     #:|OWLAPI-readFunctionalOntologyFile|
     #:|OWLAPI-parseNative|
     #:|OWLAPI-parse|
     #:update-racer
     #:check-for-updates
     #:load-racer-plugins
     #:load-racer-patches
     #:installed-plugins
     #:installed-patches
     #:load-racer-plugin
     #:load-racer-patch
     #:make-plugin-from-fasl-file
     #:swrl-create-forward-chainging-rules
     #:swrl-create-abduction-rules-if-possible
     #:get-prefixes
     #:delete-prefix-mappings
     #:|OWLAPI-restoreImage|
     #:|OWLAPI-storeImage|
     #:owlapi-add-axiom
     #:owlapi-add-axioms
     #:owlapi-axiom-loaded?
     #:owlapi-axiom-to-id
     #:owlapi-id-to-axiom
     #:owlapi-remove-axiom
     #:owlapi-remove-axioms
     #:owlapi-set-ontology-uri
     #:owlapi-abort
     #:owlapi-add-prefix
     #:owlapi-advance-progress
     #:owlapi-apply-changes
     #:owlapi-auto-add-axioms-to
     #:owlapi-auto-apply-changes
     #:owlapi-auto-batch-add-axioms-to
     #:owlapi-auto-batch-remove-axioms-from
     #:owlapi-auto-remove-axioms-from
     #:owlapi-batch-synchronize
     #:owlapi-classify
     #:owlapi-clear-changes
     #:owlapi-clear-ontologies
     #:owlapi-clear-registry
     #:owlapi-consider-declarations
     #:owlapi-contains
     #:owlapi-describe-ontologies
     #:owlapi-describe-ontology
     #:owlapi-describe-reasoner
     #:owlapi-describe-reasoners
     #:owlapi-disable-auto-mode
     #:owlapi-disable-incremental-updates
     #:owlapi-disable-lookup-mode
     #:owlapi-disable-memory-saving-mode
     #:owlapi-disable-simplified-protocol
     #:owlapi-disable-transient-axiom-mode
     #:owlapi-dispose
     #:owlapi-dispose-axiom
     #:owlapi-dispose-axioms
     #:owlapi-dispose-ontologies
     #:owlapi-dispose-ontology
     #:owlapi-dispose-reasoner
     #:owlapi-dont-register-declared-entities
     #:owlapi-dont-register-referenced-entities
     #:owlapi-enable-incremental-updates
     #:owlapi-enable-lookup-mode
     #:owlapi-enable-memory-saving-mode
     #:owlapi-enable-simplified-protocol
     #:owlapi-enable-transient-axiom-mode
     #:owlapi-export-ontology
     #:owlapi-export-reasoner
     #:owlapi-find-id-from-object
     #:owlapi-find-object-from-id
     #:owlapi-get-all-ontologies
     #:owlapi-get-ancestor-classes
     #:owlapi-get-ancestor-properties
     #:owlapi-get-annotation-axioms-for-axiom
     #:owlapi-get-auto-declare-data-properties
     #:owlapi-get-auto-ontology
     #:owlapi-get-axiom-counter
     #:owlapi-get-axioms
     #:owlapi-get-axioms-in
     #:owlapi-get-axioms-of-type
     #:owlapi-get-axioms-of-type-in
     #:owlapi-get-axioms-per-ontology
     #:owlapi-get-changes
     #:owlapi-get-current-reasoner
     #:owlapi-get-data-property-relationships
     #:owlapi-get-data-property-values
     #:owlapi-get-descendant-classes
     #:owlapi-get-descendant-properties
     #:owlapi-get-different-individuals
     #:owlapi-get-disjoint-classes
     #:owlapi-get-disjoint-data-properties
     #:owlapi-get-disjoint-object-properties
     #:owlapi-get-domains
     #:owlapi-get-equivalent-classes
     #:owlapi-get-equivalent-properties
     #:owlapi-get-inconsistent-classes
     #:owlapi-get-individuals
     #:owlapi-get-instances
     #:owlapi-get-inverse-properties
     #:owlapi-get-loaded-ontologies
     #:owlapi-get-owl-annotation-assertion-axiom
     #:owlapi-get-owl-annotation-property-domain-axiom
     #:owlapi-get-owl-annotation-property-range-axiom
     #:owlapi-get-owl-asymmetric-object-property-axiom
     #:owlapi-get-owl-axiom-annotation-axiom
     #:owlapi-get-owl-class-assertion-axiom
     #:owlapi-get-owl-data-property-assertion-axiom
     #:owlapi-get-owl-data-property-domain-axiom
     #:owlapi-get-owl-data-property-range-axiom
     #:owlapi-get-owl-data-sub-property-axiom
     #:owlapi-get-owl-datatype-definition-axiom
     #:owlapi-get-owl-declaration-axiom
     #:owlapi-get-owl-different-individuals-axiom
     #:owlapi-get-owl-disjoint-classes-axiom
     #:owlapi-get-owl-disjoint-data-properties-axiom
     #:owlapi-get-owl-disjoint-object-properties-axiom
     #:owlapi-get-owl-disjoint-union-axiom
     #:owlapi-get-owl-entity-annotation-axiom
     #:owlapi-get-owl-equivalent-classes-axiom
     #:owlapi-get-owl-equivalent-data-properties-axiom
     #:owlapi-get-owl-equivalent-object-properties-axiom
     #:owlapi-get-owl-functional-data-property-axiom
     #:owlapi-get-owl-functional-object-property-axiom
     #:owlapi-get-owl-has-key-axiom
     #:owlapi-get-owl-implicit-declaration-axiom
     #:owlapi-get-owl-imports-declaration-axiom
     #:owlapi-get-owl-inverse-functional-object-property-axiom
     #:owlapi-get-owl-inverse-object-properties-axiom
     #:owlapi-get-owl-irreflexive-object-property-axiom
     #:owlapi-get-owl-negative-data-property-assertion-axiom
     #:owlapi-get-owl-negative-object-property-assertion-axiom
     #:owlapi-get-owl-object-property-assertion-axiom
     #:owlapi-get-owl-object-property-chain-sub-property-axiom
     #:owlapi-get-owl-object-property-domain-axiom
     #:owlapi-get-owl-object-property-range-axiom
     #:owlapi-get-owl-object-sub-property-axiom
     #:owlapi-get-owl-ontology-annotation-axiom
     #:owlapi-get-owl-ontology-version-declaration-axiom
     #:owlapi-get-owl-prefix-declaration-axiom
     #:owlapi-get-owl-really-implicit-declaration-axiom
     #:owlapi-get-owl-reflexive-object-property-axiom
     #:owlapi-get-owl-same-individuals-axiom
     #:owlapi-get-owl-sub-annotation-property-axiom
     #:owlapi-get-owl-sub-annotation-property-of-axiom
     #:owlapi-get-owl-sub-class-axiom
     #:owlapi-get-owl-symmetric-object-property-axiom
     #:owlapi-get-owl-transitive-object-property-axiom
     #:owlapi-get-object-property-relationships
     #:owlapi-get-object-property-values
     #:owlapi-get-ontologies
     #:owlapi-get-prefixes
     #:owlapi-get-ranges
     #:owlapi-get-reasoners
     #:owlapi-get-related-individuals
     #:owlapi-get-related-values
     #:owlapi-get-same-individuals
     #:owlapi-get-sub-classes
     #:owlapi-get-sub-properties
     #:owlapi-get-super-classes
     #:owlapi-get-super-properties
     #:owlapi-get-types
     #:owlapi-has-data-property-relationship
     #:owlapi-has-object-property-relationship
     #:owlapi-has-type
     #:owlapi-ignore-annotations
     #:owlapi-ignore-declarations
     #:owlapi-init
     #:owlapi-is-asymmetric
     #:owlapi-is-class
     #:owlapi-is-classified
     #:owlapi-is-consistent
     #:owlapi-is-defined-class
     #:owlapi-is-defined-data-property
     #:owlapi-is-defined-individual
     #:owlapi-is-defined-object-property
     #:owlapi-is-different-individual
     #:owlapi-is-entailed
     #:owlapi-is-equivalent-class
     #:owlapi-is-functional
     #:owlapi-is-inverse-functional
     #:owlapi-is-irreflexive
     #:owlapi-is-realised
     #:owlapi-is-reflexive
     #:owlapi-is-same-individual
     #:owlapi-is-satisfiable
     #:owlapi-is-sub-class-of
     #:owlapi-is-symmetric
     #:owlapi-is-transitive
     #:owlapi-keep-annotations
     #:owlapi-load-axiom
     #:owlapi-load-axioms
     #:owlapi-load-ontologies
     #:owlapi-load-ontology
     #:owlapi-manually-apply-changes
     #:owlapi-merge-ontologies
     #:owlapi-new-ontology
     #:owlapi-new-reasoner
     #:owlapi-new-reasoner1
     #:owlapi-next-axiom-use-id
     #:owlapi-parse
     #:owlapi-parse-native
     #:owlapi-read-functional-ontology-document
     #:owlapi-read-functional-ontology-file
     #:owlapi-read-ontology
     #:owlapi-read-xml-ontology-document
     #:owlapi-read-xml-ontology-file
     #:owlapi-realize
     #:owlapi-register-declared-entities
     #:owlapi-register-last-answer
     #:owlapi-register-object
     #:owlapi-register-referenced-entities
     #:owlapi-reload-loaded-ontologies
     #:owlapi-remove-prefix
     #:owlapi-reset-axiom-counter
     #:owlapi-restore-image
     #:owlapi-save-ontology
     #:owlapi-set-auto-declare-data-properties
     #:owlapi-set-axiom-counter
     #:owlapi-set-current-reasoner
     #:owlapi-set-progress
     #:owlapi-set-progress-range
     #:owlapi-set-return-policy
     #:owlapi-sleep
     #:owlapi-store-image
     #:owlapi-unload-axiom
     #:owlapi-unload-axioms
     #:owlapi-unload-ontologies
     #:owlapi-unload-ontology
     #:owlapi-uses-incremental-updates
     #:owlapi-uses-simplified-protocol
     #:owlapi-write-functional-ontology-file
     #:owlapi-write-ontology-file
     #:owlapi-write-xml-ontology-file
     #:|OWLAPI-exportReasoner|
     #:|OWLAPI-exportOntology|
     #:|OWLAPI-SetOntologyURI|
     #:|OWLAPI-RemoveAxioms|
     #:|OWLAPI-removeAxioms|
     #:|OWLAPI-RemoveAxiom|
     #:|OWLAPI-removeAxiom|
     #:|OWLAPI-AddAxioms|
     #:|OWLAPI-addAxioms|
     #:|OWLAPI-AddAxiom|
     #:|OWLAPI-addAxiom|
     #:|OWLAPI-applyChanges|
     #:|OWLAPI-manuallyApplyChanges|
     #:|OWLAPI-autoApplyChanges|
     #:|OWLAPI-getChanges|
     #:|OWLAPI-clearChanges|
     #:|OWLAPI-getOWLObjectPropertyRangeAxiom|
     #:|OWLAPI-getOWLDataPropertyRangeAxiom|
     #:|OWLAPI-getOWLObjectPropertyDomainAxiom|
     #:|OWLAPI-getOWLDataPropertyDomainAxiom|
     #:|OWLAPI-getOWLDataSubPropertyAxiom|
     #:|OWLAPI-getOWLObjectSubPropertyAxiom|
     #:|OWLAPI-getOWLTransitiveObjectPropertyAxiom|
     #:|OWLAPI-getOWLSymmetricObjectPropertyAxiom|
     #:|OWLAPI-getOWLReflexiveObjectPropertyAxiom|
     #:|OWLAPI-getOWLIrreflexiveObjectPropertyAxiom|
     #:|OWLAPI-getOWLInverseFunctionalObjectPropertyAxiom|
     #:|OWLAPI-getOWLAsymmetricObjectPropertyAxiom|
     #:|OWLAPI-getOWLObjectPropertyChainSubPropertyAxiom|
     #:|OWLAPI-getOWLInverseObjectPropertiesAxiom|
     #:|OWLAPI-getOWLEquivalentObjectPropertiesAxiom|
     #:|OWLAPI-getOWLEquivalentDataPropertiesAxiom|
     #:|OWLAPI-getOWLDisjointObjectPropertiesAxiom|
     #:|OWLAPI-getOWLDisjointDataPropertiesAxiom|
     #:|OWLAPI-getOWLFunctionalObjectPropertyAxiom|
     #:|OWLAPI-getOWLFunctionalDataPropertyAxiom|
     #:|OWLAPI-getOWLNegativeObjectPropertyAssertionAxiom|
     #:|OWLAPI-getOWLObjectPropertyAssertionAxiom|
     #:|OWLAPI-getOWLNegativeDataPropertyAssertionAxiom|
     #:|OWLAPI-getOWLDataPropertyAssertionAxiom|
     #:|OWLAPI-getOWLSameIndividualsAxiom|
     #:|OWLAPI-getOWLDifferentIndividualsAxiom|
     #:|OWLAPI-getOWLClassAssertionAxiom|
     #:|OWLAPI-getOWLSubClassAxiom|
     #:|OWLAPI-getOWLEquivalentClassesAxiom|
     #:|OWLAPI-getOWLDisjointUnionAxiom|
     #:|OWLAPI-getOWLDisjointClassesAxiom|
     #:|OWLAPI-getOWLPrefixDeclarationAxiom|
     #:|OWLAPI-getOWLOntologyVersionDeclarationAxiom|
     #:|OWLAPI-getOWLImportsDeclarationAxiom|
     #:|OWLAPI-getOWLReallyImplicitDeclarationAxiom|
     #:|OWLAPI-getOWLImplicitDeclarationAxiom|
     #:|OWLAPI-getOWLDeclarationAxiom|
     #:|OWLAPI-getOWLAnnotationPropertyRangeAxiom|
     #:|OWLAPI-getOWLAnnotationPropertyDomainAxiom|
     #:|OWLAPI-getOWLSubAnnotationPropertyAxiom|
     #:|OWLAPI-getOWLSubAnnotationPropertyOfAxiom|
     #:|OWLAPI-getOWLAnnotationAssertionAxiom|
     #:|OWLAPI-getOWLOntologyAnnotationAxiom|
     #:|OWLAPI-getOWLEntityAnnotationAxiom|
     #:|OWLAPI-getOWLAxiomAnnotationAxiom|
     #:|OWLAPI-getOWLHasKeyAxiom|
     #:|OWLAPI-getOWLDatatypeDefinitionAxiom|
     #:|OWLAPI-getPrefixes|
     #:|OWLAPI-removePrefix|
     #:|OWLAPI-addPrefix|
     #:|OWLAPI-getAnnotationAxiomsForAxiom|
     #:|OWLAPI-getAxiomsOfTypeIn|
     #:|OWLAPI-getAxiomsOfType|
     #:|OWLAPI-getAxiomsIn|
     #:|OWLAPI-getAxiomsPerOntology|
     #:|OWLAPI-getAxioms|
     #:|OWLAPI-AxiomLoaded?|
     #:|OWLAPI-AxiomToID|
     #:|OWLAPI-IDToAxiom|
     #:|OWLAPI-disposeAxioms|
     #:|OWLAPI-disposeAxiom|
     #:|OWLAPI-unloadAxioms|
     #:|OWLAPI-unloadAxiom|
     #:|OWLAPI-loadAxioms|
     #:|OWLAPI-loadAxiom|
     #:|OWLAPI-resetAxiomCounter|
     #:|OWLAPI-setAxiomCounter|
     #:|OWLAPI-getAxiomCounter|
     #:|OWLAPI-isSatisfiable|
     #:|OWLAPI-dispose|
     #:|OWLAPI-clearOntologies|
     #:|OWLAPI-unloadOntology|
     #:|OWLAPI-unloadOntologies|
     #:|OWLAPI-isDefinedIndividual|
     #:|OWLAPI-isDefinedDataProperty|
     #:|OWLAPI-isDefinedObjectProperty|
     #:|OWLAPI-isDefinedClass|
     #:|OWLAPI-realize|
     #:|OWLAPI-isRealised|
     #:|OWLAPI-classify|
     #:|OWLAPI-isClassified|
     #:|OWLAPI-considerDeclarations|
     #:|OWLAPI-ignoreDeclarations|
     #:|OWLAPI-keepAnnotations|
     #:|OWLAPI-ignoreAnnotations|
     #:|OWLAPI-disableMemorySavingMode|
     #:|OWLAPI-enableMemorySavingMode|
     #:|OWLAPI-batchSynchronize|
     #:|OWLAPI-isEntailed|
     #:|OWLAPI-disableTransientAxiomMode|
     #:|OWLAPI-enableTransientAxiomMode|
     #:|OWLAPI-disableLookupMode|
     #:|OWLAPI-enableLookupMode|
     #:|OWLAPI-disableAutoMode|
     #:|OWLAPI-autoBatchRemoveAxiomsFrom|
     #:|OWLAPI-autoRemoveAxiomsFrom|
     #:|OWLAPI-autoBatchAddAxiomsTo|
     #:|OWLAPI-autoAddAxiomsTo|
     #:|OWLAPI-getAutoOntology|
     #:|OWLAPI-getAutoDeclareDataProperties|
     #:|OWLAPI-setAutoDeclareDataProperties|
     #:|OWLAPI-reloadLoadedOntologies|
     #:|OWLAPI-disposeOntologies|
     #:|OWLAPI-loadOntologies|
     #:|OWLAPI-getAllOntologies|
     #:|OWLAPI-contains|
     #:|OWLAPI-getLoadedOntologies|
     #:|OWLAPI-getOntologies|
     #:|OWLAPI-loadOntology|
     #:|OWLAPI-disposeOntology|
     #:|OWLAPI-mergeOntologies|
     #:|OWLAPI-newOntology|
     #:|OWLAPI-describeOntologies|
     #:|OWLAPI-describeOntology|
     #:|OWLAPI-describeReasoners|
     #:|OWLAPI-describeReasoner|
     #:|OWLAPI-isAsymmetric|
     #:|OWLAPI-isIrreflexive|
     #:|OWLAPI-isReflexive|
     #:|OWLAPI-isTransitive|
     #:|OWLAPI-isSymmetric|
     #:|OWLAPI-isInverseFunctional|
     #:|OWLAPI-getInverseProperties|
     #:|OWLAPI-getDisjointDataProperties|
     #:|OWLAPI-getDisjointObjectProperties|
     #:|OWLAPI-getDisjointClasses|
     #:|OWLAPI-isFunctional|
     #:|OWLAPI-getRanges|
     #:|OWLAPI-getDomains|
     #:|OWLAPI-getEquivalentProperties|
     #:|OWLAPI-getDescendantProperties|
     #:|OWLAPI-getAncestorProperties|
     #:|OWLAPI-getSubProperties|
     #:|OWLAPI-getSuperProperties|
     #:|OWLAPI-getDifferentIndividuals|
     #:|OWLAPI-getDataPropertyValues|
     #:|OWLAPI-getObjectPropertyValues|
     #:|OWLAPI-getInstances|
     #:|OWLAPI-isDifferentIndividual|
     #:|OWLAPI-isSameIndividual|
     #:|OWLAPI-getSameIndividuals|
     #:|OWLAPI-getRelatedValues|
     #:|OWLAPI-getRelatedIndividuals|
     #:|OWLAPI-hasDataPropertyRelationship|
     #:|OWLAPI-hasObjectPropertyRelationship|
     #:|OWLAPI-hasType|
     #:|OWLAPI-getDataPropertyRelationships|
     #:|OWLAPI-getObjectPropertyRelationships|
     #:|OWLAPI-getIndividuals|
     #:|OWLAPI-getTypes|
     #:|OWLAPI-isConsistent|
     #:|OWLAPI-getInconsistentClasses|
     #:|OWLAPI-getEquivalentClasses|
     #:|OWLAPI-getDescendantClasses|
     #:|OWLAPI-getSubClasses|
     #:|OWLAPI-getAncestorClasses|
     #:|OWLAPI-getSuperClasses|
     #:|OWLAPI-isEquivalentClass|
     #:|OWLAPI-isSubClassOf|
     #:|OWLAPI-isClass|
     #:|OWLAPI-findIDFromObject|
     #:|OWLAPI-findObjectFromID|
     #:|OWLAPI-registerObject|
     #:|OWLAPI-registerLastAnswer|
     #:|OWLAPI-clearRegistry|
     #:|OWLAPI-setReturnPolicy|
     #:|OWLAPI-nextAxiomUseID|
     #:|OWLAPI-dontRegisterDeclaredEntities|
     #:|OWLAPI-registerDeclaredEntities|
     #:|OWLAPI-dontRegisterReferencedEntities|
     #:|OWLAPI-registerReferencedEntities|
     #:|OWLAPI-usesIncrementalUpdates|
     #:|OWLAPI-disableIncrementalUpdates|
     #:|OWLAPI-enableIncrementalUpdates|
     #:|OWLAPI-usesSimplifiedProtocol|
     #:|OWLAPI-disableSimplifiedProtocol|
     #:|OWLAPI-enableSimplifiedProtocol|
     #:|OWLAPI-advanceProgress|
     #:|OWLAPI-setProgress|
     #:|OWLAPI-setProgressRange|
     #:|OWLAPI-init|
     #:|OWLAPI-abort|
     #:|OWLAPI-sleep|
     #:|OWLAPI-getReasoners|
     #:|OWLAPI-getCurrentReasoner|
     #:|OWLAPI-setCurrentReasoner|
     #:|OWLAPI-disposeReasoner|
     #:|OWLAPI-newReasoner|
     #:|OWLAPI-newReasoner1|
     #:get-agraph-version
     #:get-nrql-version
     #:restore-server-image
     #:store-server-image
     #:restore-all-substrates
     #:restore-substrate
     #:store-all-substrates
     #:store-substrate-for-abox
     #:check-nrql-subscriptions
     #:disable-rcc-substrate-mirroring
     #:enable-rcc-substrate-mirroring
     #:del-rcc-edge1
     #:del-rcc-node1
     #:rcc-edge-description1
     #:rcc-node-description1
     #:rcc-edge-label1
     #:rcc-node-label1
     #:rcc-edge1
     #:rcc-node1
     #:rcc-related1
     #:rcc-instance1
     #:delete-rcc-synonyms
     #:register-rcc-synonym
     #:rcc-consistent-p
     #:create-rcc-edge
     #:create-rcc-node
     #:set-rcc-box
     #:set-mirror-data-box
     #:get-edge-label-for-non-existent-edges
     #:set-edge-label-for-non-existent-edges
     #:description-implies-p
     #:edge-description1
     #:node-description1
     #:edge-label1
     #:node-label1
     #:del-data-edge1
     #:del-data-node1
     #:data-edge1
     #:data-node1
     #:set-data-box
     #:get-data-edge-description
     #:get-data-edge-label
     #:get-data-node-description
     #:get-data-node-label
     #:delete-data-edge
     #:delete-data-node
     #:create-data-edge
     #:create-data-node
     #:describe-all-edges
     #:get-substrate-edges
     #:describe-all-nodes
     #:get-substrate-nodes
     #:describe-all-substrates
     #:describe-substrate
     #:rmi
     #:get-proxy-server
     #:set-proxy-server
     #:check-ontology
     #:check-concept-coherence
     #:restore-standard-settings
     #:set-nrql-mode
     #:disable-query-realization
     #:enable-query-realization
     #:disable-query-repository
     #:enable-query-repository
     #:dont-report-inconsistent-queries-and-rules
     #:report-inconsistent-queries-and-rules
     #:describe-query-processing-mode
     #:describe-current-substrate
     #:get-process-pool-size
     #:get-maximum-size-of-process-pool
     #:get-initial-size-of-process-pool
     #:set-maximum-size-of-process-pool
     #:set-initial-size-of-process-pool
     #:set-rewrite-defined-concepts
     #:optimizer-dont-ensure-late-lambda-evaluation
     #:optimizer-ensure-late-lambda-evaluation
     #:optimizer-dont-use-cardinality-heuristics
     #:optimizer-use-cardinality-heuristics
     #:optimizer-get-time-bound
     #:optimizer-set-time-bound
     #:optimizer-get-no-of-plans-upper-bound
     #:optimizer-set-no-of-plans-upper-bound
     #:disable-query-optimization
     #:enable-query-optimization
     #:include-permutations
     #:exclude-permutations
     #:dont-add-rule-consequences-automatically
     #:add-rule-consequences-automatically
     #:process-set-at-a-time
     #:process-tuple-at-a-time
     #:get-max-no-of-tuples-bound
     #:set-max-no-of-tuples-bound
     #:dont-check-abox-consistency-before-querying
     #:check-abox-consistency-before-querying
     #:enable-lazy-tuple-computation
     #:enable-eager-tuple-computation
     #:dont-add-role-assertions-for-datatype-properties
     #:add-role-assertions-for-datatype-properties
     #:disable-told-information-querying
     #:enable-told-information-querying
     #:disable-nrql-warnings
     #:enable-nrql-warnings
     #:disable-kb-has-changed-warning-tokens
     #:enable-kb-has-changed-warning-tokens
     #:disable-phase-two-starts-warning-tokens
     #:enable-phase-two-starts-warning-tokens
     #:disable-two-phase-query-processing-mode
     #:enable-two-phase-query-processing-mode
     #:enable-very-smart-abox-mirroring
     #:enable-smart-abox-mirroring
     #:disable-abox-mirroring
     #:enable-abox-mirroring
     #:dont-use-injective-variables-by-default
     #:use-injective-variables-by-default
     #:dont-use-individual-synonym-equivalence-classes
     #:use-individual-synonym-equivalence-classes
     #:dont-add-missing-top-conjuncts
     #:add-missing-top-conjuncts
     #:disable-data-substrate-mirroring
     #:enable-data-substrate-mirroring
     #:wait-for-rules-to-terminate
     #:wait-for-queries-to-terminate
     #:get-all-answers
     #:execute-or-reexecute-all-rules
     #:run-all-rules
     #:reexecute-all-rules
     #:execute-all-rules
     #:execute-or-reexecute-all-queries
     #:reexecute-all-queries
     #:run-all-queries
     #:execute-all-queries
     #:abort-all-rules
     #:abort-all-queries
     #:describe-all-definitions
     #:describe-definition
     #:delete-all-definitions
     #:activate-defined-query
     #:deactivate-defined-query
     #:dont-keep-defined-query-atoms
     #:keep-defined-query-atoms
     #:enable-lazy-unfolding-of-defined-queries
     #:disable-lazy-unfolding-of-defined-queries
     #:enable-defined-queries
     #:disable-defined-queries
     #:dont-prefer-defined-queries
     #:prefer-defined-queries
     #:dont-allow-overloaded-definitions
     #:allow-overloaded-definitions
     #:undefine-query
     #:define-and-prepare-query
     #:define-and-execute-query
     #:define-query
     #:inaccurate-rules
     #:accurate-rules
     #:inaccurate-queries
     #:accurate-queries
     #:sleeping-expensive-rules
     #:sleeping-cheap-rules
     #:waiting-expensive-rules
     #:waiting-cheap-rules
     #:sleeping-expensive-queries
     #:sleeping-cheap-queries
     #:waiting-expensive-queries
     #:waiting-cheap-queries
     #:running-expensive-rules
     #:running-cheap-rules
     #:running-expensive-queries
     #:running-cheap-queries
     #:expensive-rules
     #:cheap-rules
     #:expensive-queries
     #:cheap-queries
     #:terminated-rules
     #:processed-rules
     #:terminated-queries
     #:processed-queries
     #:sleeping-rules
     #:waiting-rules
     #:sleeping-queries
     #:waiting-queries
     #:running-rules
     #:running-queries
     #:active-rules
     #:active-queries
     #:prepared-rules
     #:ready-rules
     #:prepared-queries
     #:ready-queries
     #:answer-tbox-query1
     #:answer-tbox-query
     #:racer-answer-tbox-query1
     #:racer-answer-tbox-query
     #:racer-prepare-tbox-query1
     #:racer-prepare-tbox-query
     #:move-rules
     #:copy-rules
     #:apply-rule-under-premise1
     #:apply-rule-under-premise
     #:apply-rule
     #:racer-apply-rule-under-premise1
     #:racer-apply-rule1
     #:racer-apply-rule-under-premise
     #:racer-apply-rule
     #:prepare-rule1
     #:prepare-rule
     #:racer-prepare-rule1
     #:racer-prepare-rule
     #:answer-query-under-premise1
     #:answer-query-under-premise
     #:racer-answer-query-under-premise1
     #:racer-answer-query-under-premise
     #:answer-query1
     #:answer-query
     #:racer-answer-query1
     #:racer-answer-query
     #:get-answer-size
     #:prepare-query1
     #:prepare-query
     #:racer-prepare-query1
     #:racer-prepare-query
     #:delete-all-rules
     #:delete-all-queries
     #:describe-all-rules
     #:describe-all-queries
     #:all-rules
     #:all-queries
     #:all-different-from-assertions
     #:all-same-as-assertions
     #:get-abox-graph
     #:get-role-hierarchy
     #:get-concept-properties
     #:get-individual-annotation-fillers
     #:get-individual-annotation-datatype-fillers
     #:get-individual-datatype-fillers
     #:get-individual-successors
     #:prepare-nrql-engine
     #:in-unsafe-mode?
     #:exit-server
     #:full-reset
     #:reset-nrql-engine
     #:all-substrates
     #:delete-all-substrates
     #:get-substrate-type
     #:set-substrate-type
     #:reset-all-substrates
     #:server-value
     #:get-all-server-values
     #:get-all-values
     #:unbind-all
     #:unbind1
     #:defpar1
     #:defcon1
     #:server-function
     #:get-all-server-functions
     #:get-all-functions
     #:fcall
     #:undefine-all
     #:undefine1
     #:define1
     #:evaluate1
     #:set-racer-parameter
     #:add-explanation-assertions
     #:get-explanations
     #:get-number-of-explanations
     #:query-subscribers
     #:unsubscribe-from
     #:subscribe-to
     #:get-nodes-in-qbox-for-abox
     #:get-dag-of-qbox-for-abox
     #:show-qbox-for-abox
     #:query-equivalents
     #:query-descendants
     #:query-children
     #:query-ancestors
     #:query-parents
     #:query-equivalent-p
     #:query-entails-p
     #:classify-query
     #:rule-consistent-p
     #:query-consistent-p
     #:add-chosen-sets-of-rule-consequences
     #:get-chosen-sets-of-rule-consequences
     #:choose-current-set-of-rule-consequences
     #:execute-applicable-rules
     #:unapplicable-rules
     #:applicable-rules
     #:rule-unapplicable-p
     #:rule-applicable-p
     #:execute-or-reexecute-rule
     #:execute-or-reexecute-query
     #:reexecute-rule
     #:reexecute-query
     #:reprepare-rule
     #:reprepare-query
     #:rule-accurate-p
     #:query-accurate-p
     #:expensive-rule-p
     #:expensive-query-p
     #:cheap-rule-p
     #:cheap-query-p
     #:rule-terminated-p
     #:query-terminated-p
     #:rule-processed-p
     #:query-processed-p
     #:rule-sleeping-p
     #:query-sleeping-p
     #:rule-waiting-p
     #:query-waiting-p
     #:rule-running-p
     #:query-running-p
     #:rule-active-p
     #:query-active-p
     #:rule-prepared-p
     #:query-prepared-p
     #:rule-ready-p
     #:query-ready-p
     #:execute-rule
     #:get-all-remaining-sets-of-rule-consequences
     #:get-next-n-remaining-sets-of-rule-consequences
     #:get-next-set-of-rule-consequences
     #:next-set-of-rule-consequences-available-p
     #:get-current-set-of-rule-consequences
     #:get-all-remaining-tuples
     #:get-next-n-remaining-tuples
     #:get-next-tuple
     #:next-tuple-available-p
     #:get-current-tuple
     #:get-answer
     #:abort-rule
     #:abort-query
     #:execute-query
     #:delete-rule
     #:delete-query
     #:original-rule-antecedence
     #:original-query-body
     #:rule-antecedence
     #:query-body
     #:original-rule-consequence
     #:original-query-head
     #:rule-consequence
     #:query-head
     #:describe-rule
     #:describe-query
     #:describe-rule-status
     #:describe-query-status
     #:add-doc-phrase
     #:add-doc-image-data
     #:add-doc-image-data-from-file
     #:add-doc-image-file
     #:del-doc-entry
     #:add-doc-entry
     #:compute-abox-difference-alternative
     #:compute-abox-difference
     #:retrieve-with-explanation
     #:del-rcc-edge
     #:del-rcc-node
     #:rcc-edge-description
     #:rcc-node-description
     #:rcc-edge-label
     #:rcc-node-label
     #:rcc-edge
     #:rcc-node
     #:rcc-related
     #:rcc-instance
     #:rcc-synonym
     #:rcc-consistent?
     #:in-rcc-box
     #:in-mirror-data-box
     #:description-implies?
     #:edge-description
     #:node-description
     #:edge-label
     #:node-label
     #:del-data-edge
     #:del-data-node
     #:data-edge
     #:data-node
     #:in-data-box
     #:undefquery
     #:def-and-exec-query
     #:def-and-prep-query
     #:defquery
     #:tbox-retrieve1
     #:tbox-retrieve
     #:prepare-tbox-query1
     #:prepare-tbox-query
     #:firerule-under-premise1
     #:firerule-under-premise
     #:firerule1
     #:firerule
     #:apply-abox-rule-under-premise1
     #:apply-abox-rule-under-premise
     #:apply-abox-rule1
     #:apply-abox-rule
     #:preprule1
     #:preprule
     #:prepare-abox-rule1
     #:prepare-abox-rule
     #:retrieve-under-premise1
     #:retrieve-under-premise
     #:retrieve1
     #:retrieve
     #:prepare-abox-query1
     #:prepare-abox-query
     #:unbind
     #:defpar
     #:defcon
     #:undefine
     #:define
     #:evaluate
     #:with-future-bindings-evaluated
     #:with-future-bindings
     #:with-bindings-evaluated
     #:with-bindings
     #:with-nrql-settings-evaluated
     #:with-nrql-settings
     ))

