(in-package owlapi)

;;;
;;;----------------------------------------------
;;;   Automatically Generated OWLAPI Synonyms   
;;;          Version: 2.0, Build: 2013-03-07 
;;;          Date: March 07 2013, 13:05  
;;;----------------------------------------------
;;;
(progn
  (owlapi-defun (owlapi-write-xml-ontology-file)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-writeXMLOntologyFile| common-lisp-user::args))
  (owlapi-defun (owlapi-write-ontology-file)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-writeOntologyFile| common-lisp-user::args))
  (owlapi-defun (owlapi-write-functional-ontology-file)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-writeFunctionalOntologyFile|
           common-lisp-user::args))
  (owlapi-defun (owlapi-uses-simplified-protocol)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-usesSimplifiedProtocol| common-lisp-user::args))
  (owlapi-defun (owlapi-uses-incremental-updates)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-usesIncrementalUpdates| common-lisp-user::args))
  (owlapi-defun (owlapi-unload-ontology) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-unloadOntology| common-lisp-user::args))
  (owlapi-defun (owlapi-unload-ontologies)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-unloadOntologies| common-lisp-user::args))
  (owlapi-defun (owlapi-unload-axioms) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-unloadAxioms| common-lisp-user::args))
  (owlapi-defun (owlapi-unload-axiom) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-unloadAxiom| common-lisp-user::args))
  (owlapi-defun (owlapi-store-image) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-storeImage| common-lisp-user::args))
  (owlapi-defun (owlapi-sleep) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-sleep| common-lisp-user::args))
  (owlapi-defun (owlapi-set-return-policy)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-setReturnPolicy| common-lisp-user::args))
  (owlapi-defun (owlapi-set-progress-range)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-setProgressRange| common-lisp-user::args))
  (owlapi-defun (owlapi-set-progress) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-setProgress| common-lisp-user::args))
  (owlapi-defun (owlapi-set-current-reasoner)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-setCurrentReasoner| common-lisp-user::args))
  (owlapi-defun (owlapi-set-axiom-counter)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-setAxiomCounter| common-lisp-user::args))
  (owlapi-defun (owlapi-set-auto-declare-data-properties)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-setAutoDeclareDataProperties|
           common-lisp-user::args))
  (owlapi-defun (owlapi-save-ontology) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-saveOntology| common-lisp-user::args))
  (owlapi-defun (owlapi-restore-image) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-restoreImage| common-lisp-user::args))
  (owlapi-defun (owlapi-reset-axiom-counter)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-resetAxiomCounter| common-lisp-user::args))
  (owlapi-defun (owlapi-remove-prefix) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-removePrefix| common-lisp-user::args))
  (owlapi-defun (owlapi-reload-loaded-ontologies)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-reloadLoadedOntologies| common-lisp-user::args))
  (owlapi-defun (owlapi-register-referenced-entities)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-registerReferencedEntities|
           common-lisp-user::args))
  (owlapi-defun (owlapi-register-object) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-registerObject| common-lisp-user::args))
  (owlapi-defun (owlapi-register-last-answer)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-registerLastAnswer| common-lisp-user::args))
  (owlapi-defun (owlapi-register-declared-entities)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-registerDeclaredEntities| common-lisp-user::args))
  (owlapi-defun (owlapi-realize) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-realize| common-lisp-user::args))
  (owlapi-defun (owlapi-read-xml-ontology-file)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-readXMLOntologyFile| common-lisp-user::args))
  (owlapi-defun (owlapi-read-xml-ontology-document)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-readXMLOntologyDocument| common-lisp-user::args))
  (owlapi-defun (owlapi-read-ontology) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-readOntology| common-lisp-user::args))
  (owlapi-defun (owlapi-read-functional-ontology-file)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-readFunctionalOntologyFile|
           common-lisp-user::args))
  (owlapi-defun (owlapi-read-functional-ontology-document)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-readFunctionalOntologyDocument|
           common-lisp-user::args))
  (owlapi-defun (owlapi-parse-native) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-parseNative| common-lisp-user::args))
  (owlapi-defun (owlapi-parse) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-parse| common-lisp-user::args))
  (owlapi-defun (owlapi-next-axiom-use-id)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-nextAxiomUseID| common-lisp-user::args))
  (owlapi-defun (owlapi-new-reasoner1) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-newReasoner1| common-lisp-user::args))
  (owlapi-defun (owlapi-new-reasoner) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-newReasoner| common-lisp-user::args))
  (owlapi-defun (owlapi-new-ontology) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-newOntology| common-lisp-user::args))
  (owlapi-defun (owlapi-merge-ontologies)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-mergeOntologies| common-lisp-user::args))
  (owlapi-defun (owlapi-manually-apply-changes)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-manuallyApplyChanges| common-lisp-user::args))
  (owlapi-defun (owlapi-load-ontology) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-loadOntology| common-lisp-user::args))
  (owlapi-defun (owlapi-load-ontologies) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-loadOntologies| common-lisp-user::args))
  (owlapi-defun (owlapi-load-axioms) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-loadAxioms| common-lisp-user::args))
  (owlapi-defun (owlapi-load-axiom) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-loadAxiom| common-lisp-user::args))
  (owlapi-defun (owlapi-keep-annotations)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-keepAnnotations| common-lisp-user::args))
  (owlapi-defun (owlapi-is-transitive) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-isTransitive| common-lisp-user::args))
  (owlapi-defun (owlapi-is-symmetric) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-isSymmetric| common-lisp-user::args))
  (owlapi-defun (owlapi-is-sub-class-of) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-isSubClassOf| common-lisp-user::args))
  (owlapi-defun (owlapi-is-satisfiable) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-isSatisfiable| common-lisp-user::args))
  (owlapi-defun (owlapi-is-same-individual)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-isSameIndividual| common-lisp-user::args))
  (owlapi-defun (owlapi-is-reflexive) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-isReflexive| common-lisp-user::args))
  (owlapi-defun (owlapi-is-realised) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-isRealised| common-lisp-user::args))
  (owlapi-defun (owlapi-is-irreflexive) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-isIrreflexive| common-lisp-user::args))
  (owlapi-defun (owlapi-is-inverse-functional)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-isInverseFunctional| common-lisp-user::args))
  (owlapi-defun (owlapi-is-functional) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-isFunctional| common-lisp-user::args))
  (owlapi-defun (owlapi-is-equivalent-class)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-isEquivalentClass| common-lisp-user::args))
  (owlapi-defun (owlapi-is-entailed) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-isEntailed| common-lisp-user::args))
  (owlapi-defun (owlapi-is-different-individual)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-isDifferentIndividual| common-lisp-user::args))
  (owlapi-defun (owlapi-is-defined-object-property)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-isDefinedObjectProperty| common-lisp-user::args))
  (owlapi-defun (owlapi-is-defined-individual)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-isDefinedIndividual| common-lisp-user::args))
  (owlapi-defun (owlapi-is-defined-data-property)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-isDefinedDataProperty| common-lisp-user::args))
  (owlapi-defun (owlapi-is-defined-class)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-isDefinedClass| common-lisp-user::args))
  (owlapi-defun (owlapi-is-consistent) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-isConsistent| common-lisp-user::args))
  (owlapi-defun (owlapi-is-classified) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-isClassified| common-lisp-user::args))
  (owlapi-defun (owlapi-is-class) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-isClass| common-lisp-user::args))
  (owlapi-defun (owlapi-is-asymmetric) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-isAsymmetric| common-lisp-user::args))
  (owlapi-defun (owlapi-init) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-init| common-lisp-user::args))
  (owlapi-defun (owlapi-ignore-declarations)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-ignoreDeclarations| common-lisp-user::args))
  (owlapi-defun (owlapi-ignore-annotations)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-ignoreAnnotations| common-lisp-user::args))
  (owlapi-defun (owlapi-has-type) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-hasType| common-lisp-user::args))
  (owlapi-defun (owlapi-has-object-property-relationship)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-hasObjectPropertyRelationship|
           common-lisp-user::args))
  (owlapi-defun (owlapi-has-data-property-relationship)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-hasDataPropertyRelationship|
           common-lisp-user::args))
  (owlapi-defun (owlapi-get-types) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getTypes| common-lisp-user::args))
  (owlapi-defun (owlapi-get-super-properties)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getSuperProperties| common-lisp-user::args))
  (owlapi-defun (owlapi-get-super-classes)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getSuperClasses| common-lisp-user::args))
  (owlapi-defun (owlapi-get-sub-properties)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getSubProperties| common-lisp-user::args))
  (owlapi-defun (owlapi-get-sub-classes) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getSubClasses| common-lisp-user::args))
  (owlapi-defun (owlapi-get-same-individuals)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getSameIndividuals| common-lisp-user::args))
  (owlapi-defun (owlapi-get-related-values)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getRelatedValues| common-lisp-user::args))
  (owlapi-defun (owlapi-get-related-individuals)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getRelatedIndividuals| common-lisp-user::args))
  (owlapi-defun (owlapi-get-reasoners) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getReasoners| common-lisp-user::args))
  (owlapi-defun (owlapi-get-ranges) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getRanges| common-lisp-user::args))
  (owlapi-defun (owlapi-get-prefixes) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getPrefixes| common-lisp-user::args))
  (owlapi-defun (owlapi-get-ontologies) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getOntologies| common-lisp-user::args))
  (owlapi-defun (owlapi-get-object-property-values)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getObjectPropertyValues| common-lisp-user::args))
  (owlapi-defun (owlapi-get-object-property-relationships)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getObjectPropertyRelationships|
           common-lisp-user::args))
  (owlapi-defun (owlapi-get-owl-transitive-object-property-axiom)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getOWLTransitiveObjectPropertyAxiom|
           common-lisp-user::args))
  (owlapi-defun (owlapi-get-owl-symmetric-object-property-axiom)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getOWLSymmetricObjectPropertyAxiom|
           common-lisp-user::args))
  (owlapi-defun (owlapi-get-owl-sub-class-axiom)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getOWLSubClassAxiom| common-lisp-user::args))
  (owlapi-defun (owlapi-get-owl-sub-annotation-property-of-axiom)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getOWLSubAnnotationPropertyOfAxiom|
           common-lisp-user::args))
  (owlapi-defun (owlapi-get-owl-sub-annotation-property-axiom)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getOWLSubAnnotationPropertyAxiom|
           common-lisp-user::args))
  (owlapi-defun (owlapi-get-owl-same-individuals-axiom)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getOWLSameIndividualsAxiom|
           common-lisp-user::args))
  (owlapi-defun (owlapi-get-owl-reflexive-object-property-axiom)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getOWLReflexiveObjectPropertyAxiom|
           common-lisp-user::args))
  (owlapi-defun (owlapi-get-owl-really-implicit-declaration-axiom)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getOWLReallyImplicitDeclarationAxiom|
           common-lisp-user::args))
  (owlapi-defun (owlapi-get-owl-prefix-declaration-axiom)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getOWLPrefixDeclarationAxiom|
           common-lisp-user::args))
  (owlapi-defun (owlapi-get-owl-ontology-version-declaration-axiom)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getOWLOntologyVersionDeclarationAxiom|
           common-lisp-user::args))
  (owlapi-defun (owlapi-get-owl-ontology-annotation-axiom)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getOWLOntologyAnnotationAxiom|
           common-lisp-user::args))
  (owlapi-defun (owlapi-get-owl-object-sub-property-axiom)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getOWLObjectSubPropertyAxiom|
           common-lisp-user::args))
  (owlapi-defun (owlapi-get-owl-object-property-range-axiom)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getOWLObjectPropertyRangeAxiom|
           common-lisp-user::args))
  (owlapi-defun (owlapi-get-owl-object-property-domain-axiom)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getOWLObjectPropertyDomainAxiom|
           common-lisp-user::args))
  (owlapi-defun (owlapi-get-owl-object-property-chain-sub-property-axiom)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getOWLObjectPropertyChainSubPropertyAxiom|
           common-lisp-user::args))
  (owlapi-defun (owlapi-get-owl-object-property-assertion-axiom)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getOWLObjectPropertyAssertionAxiom|
           common-lisp-user::args))
  (owlapi-defun (owlapi-get-owl-negative-object-property-assertion-axiom)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getOWLNegativeObjectPropertyAssertionAxiom|
           common-lisp-user::args))
  (owlapi-defun (owlapi-get-owl-negative-data-property-assertion-axiom)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getOWLNegativeDataPropertyAssertionAxiom|
           common-lisp-user::args))
  (owlapi-defun (owlapi-get-owl-irreflexive-object-property-axiom)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getOWLIrreflexiveObjectPropertyAxiom|
           common-lisp-user::args))
  (owlapi-defun (owlapi-get-owl-inverse-object-properties-axiom)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getOWLInverseObjectPropertiesAxiom|
           common-lisp-user::args))
  (owlapi-defun (owlapi-get-owl-inverse-functional-object-property-axiom)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getOWLInverseFunctionalObjectPropertyAxiom|
           common-lisp-user::args))
  (owlapi-defun (owlapi-get-owl-imports-declaration-axiom)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getOWLImportsDeclarationAxiom|
           common-lisp-user::args))
  (owlapi-defun (owlapi-get-owl-implicit-declaration-axiom)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getOWLImplicitDeclarationAxiom|
           common-lisp-user::args))
  (owlapi-defun (owlapi-get-owl-has-key-axiom)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getOWLHasKeyAxiom| common-lisp-user::args))
  (owlapi-defun (owlapi-get-owl-functional-object-property-axiom)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getOWLFunctionalObjectPropertyAxiom|
           common-lisp-user::args))
  (owlapi-defun (owlapi-get-owl-functional-data-property-axiom)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getOWLFunctionalDataPropertyAxiom|
           common-lisp-user::args))
  (owlapi-defun (owlapi-get-owl-equivalent-object-properties-axiom)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getOWLEquivalentObjectPropertiesAxiom|
           common-lisp-user::args))
  (owlapi-defun (owlapi-get-owl-equivalent-data-properties-axiom)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getOWLEquivalentDataPropertiesAxiom|
           common-lisp-user::args))
  (owlapi-defun (owlapi-get-owl-equivalent-classes-axiom)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getOWLEquivalentClassesAxiom|
           common-lisp-user::args))
  (owlapi-defun (owlapi-get-owl-entity-annotation-axiom)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getOWLEntityAnnotationAxiom|
           common-lisp-user::args))
  (owlapi-defun (owlapi-get-owl-disjoint-union-axiom)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getOWLDisjointUnionAxiom| common-lisp-user::args))
  (owlapi-defun (owlapi-get-owl-disjoint-object-properties-axiom)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getOWLDisjointObjectPropertiesAxiom|
           common-lisp-user::args))
  (owlapi-defun (owlapi-get-owl-disjoint-data-properties-axiom)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getOWLDisjointDataPropertiesAxiom|
           common-lisp-user::args))
  (owlapi-defun (owlapi-get-owl-disjoint-classes-axiom)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getOWLDisjointClassesAxiom|
           common-lisp-user::args))
  (owlapi-defun (owlapi-get-owl-different-individuals-axiom)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getOWLDifferentIndividualsAxiom|
           common-lisp-user::args))
  (owlapi-defun (owlapi-get-owl-declaration-axiom)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getOWLDeclarationAxiom| common-lisp-user::args))
  (owlapi-defun (owlapi-get-owl-datatype-definition-axiom)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getOWLDatatypeDefinitionAxiom|
           common-lisp-user::args))
  (owlapi-defun (owlapi-get-owl-data-sub-property-axiom)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getOWLDataSubPropertyAxiom|
           common-lisp-user::args))
  (owlapi-defun (owlapi-get-owl-data-property-range-axiom)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getOWLDataPropertyRangeAxiom|
           common-lisp-user::args))
  (owlapi-defun (owlapi-get-owl-data-property-domain-axiom)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getOWLDataPropertyDomainAxiom|
           common-lisp-user::args))
  (owlapi-defun (owlapi-get-owl-data-property-assertion-axiom)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getOWLDataPropertyAssertionAxiom|
           common-lisp-user::args))
  (owlapi-defun (owlapi-get-owl-class-assertion-axiom)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getOWLClassAssertionAxiom|
           common-lisp-user::args))
  (owlapi-defun (owlapi-get-owl-axiom-annotation-axiom)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getOWLAxiomAnnotationAxiom|
           common-lisp-user::args))
  (owlapi-defun (owlapi-get-owl-asymmetric-object-property-axiom)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getOWLAsymmetricObjectPropertyAxiom|
           common-lisp-user::args))
  (owlapi-defun (owlapi-get-owl-annotation-property-range-axiom)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getOWLAnnotationPropertyRangeAxiom|
           common-lisp-user::args))
  (owlapi-defun (owlapi-get-owl-annotation-property-domain-axiom)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getOWLAnnotationPropertyDomainAxiom|
           common-lisp-user::args))
  (owlapi-defun (owlapi-get-owl-annotation-assertion-axiom)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getOWLAnnotationAssertionAxiom|
           common-lisp-user::args))
  (owlapi-defun (owlapi-get-loaded-ontologies)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getLoadedOntologies| common-lisp-user::args))
  (owlapi-defun (owlapi-get-inverse-properties)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getInverseProperties| common-lisp-user::args))
  (owlapi-defun (owlapi-get-instances) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getInstances| common-lisp-user::args))
  (owlapi-defun (owlapi-get-individuals) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getIndividuals| common-lisp-user::args))
  (owlapi-defun (owlapi-get-inconsistent-classes)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getInconsistentClasses| common-lisp-user::args))
  (owlapi-defun (owlapi-get-equivalent-properties)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getEquivalentProperties| common-lisp-user::args))
  (owlapi-defun (owlapi-get-equivalent-classes)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getEquivalentClasses| common-lisp-user::args))
  (owlapi-defun (owlapi-get-domains) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getDomains| common-lisp-user::args))
  (owlapi-defun (owlapi-get-disjoint-object-properties)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getDisjointObjectProperties|
           common-lisp-user::args))
  (owlapi-defun (owlapi-get-disjoint-data-properties)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getDisjointDataProperties|
           common-lisp-user::args))
  (owlapi-defun (owlapi-get-disjoint-classes)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getDisjointClasses| common-lisp-user::args))
  (owlapi-defun (owlapi-get-different-individuals)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getDifferentIndividuals| common-lisp-user::args))
  (owlapi-defun (owlapi-get-descendant-properties)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getDescendantProperties| common-lisp-user::args))
  (owlapi-defun (owlapi-get-descendant-classes)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getDescendantClasses| common-lisp-user::args))
  (owlapi-defun (owlapi-get-data-property-values)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getDataPropertyValues| common-lisp-user::args))
  (owlapi-defun (owlapi-get-data-property-relationships)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getDataPropertyRelationships|
           common-lisp-user::args))
  (owlapi-defun (owlapi-get-current-reasoner)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getCurrentReasoner| common-lisp-user::args))
  (owlapi-defun (owlapi-get-changes) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getChanges| common-lisp-user::args))
  (owlapi-defun (owlapi-get-axioms-per-ontology)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getAxiomsPerOntology| common-lisp-user::args))
  (owlapi-defun (owlapi-get-axioms-of-type-in)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getAxiomsOfTypeIn| common-lisp-user::args))
  (owlapi-defun (owlapi-get-axioms-of-type)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getAxiomsOfType| common-lisp-user::args))
  (owlapi-defun (owlapi-get-axioms-in) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getAxiomsIn| common-lisp-user::args))
  (owlapi-defun (owlapi-get-axioms) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getAxioms| common-lisp-user::args))
  (owlapi-defun (owlapi-get-axiom-counter)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getAxiomCounter| common-lisp-user::args))
  (owlapi-defun (owlapi-get-auto-ontology)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getAutoOntology| common-lisp-user::args))
  (owlapi-defun (owlapi-get-auto-declare-data-properties)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getAutoDeclareDataProperties|
           common-lisp-user::args))
  (owlapi-defun (owlapi-get-annotation-axioms-for-axiom)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getAnnotationAxiomsForAxiom|
           common-lisp-user::args))
  (owlapi-defun (owlapi-get-ancestor-properties)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getAncestorProperties| common-lisp-user::args))
  (owlapi-defun (owlapi-get-ancestor-classes)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getAncestorClasses| common-lisp-user::args))
  (owlapi-defun (owlapi-get-all-ontologies)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-getAllOntologies| common-lisp-user::args))
  (owlapi-defun (owlapi-find-object-from-id)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-findObjectFromID| common-lisp-user::args))
  (owlapi-defun (owlapi-find-id-from-object)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-findIDFromObject| common-lisp-user::args))
  (owlapi-defun (owlapi-export-reasoner) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-exportReasoner| common-lisp-user::args))
  (owlapi-defun (owlapi-export-ontology) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-exportOntology| common-lisp-user::args))
  (owlapi-defun (owlapi-enable-transient-axiom-mode)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-enableTransientAxiomMode| common-lisp-user::args))
  (owlapi-defun (owlapi-enable-simplified-protocol)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-enableSimplifiedProtocol| common-lisp-user::args))
  (owlapi-defun (owlapi-enable-memory-saving-mode)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-enableMemorySavingMode| common-lisp-user::args))
  (owlapi-defun (owlapi-enable-lookup-mode)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-enableLookupMode| common-lisp-user::args))
  (owlapi-defun (owlapi-enable-incremental-updates)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-enableIncrementalUpdates| common-lisp-user::args))
  (owlapi-defun (owlapi-dont-register-referenced-entities)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-dontRegisterReferencedEntities|
           common-lisp-user::args))
  (owlapi-defun (owlapi-dont-register-declared-entities)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-dontRegisterDeclaredEntities|
           common-lisp-user::args))
  (owlapi-defun (owlapi-dispose-reasoner)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-disposeReasoner| common-lisp-user::args))
  (owlapi-defun (owlapi-dispose-ontology)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-disposeOntology| common-lisp-user::args))
  (owlapi-defun (owlapi-dispose-ontologies)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-disposeOntologies| common-lisp-user::args))
  (owlapi-defun (owlapi-dispose-axioms) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-disposeAxioms| common-lisp-user::args))
  (owlapi-defun (owlapi-dispose-axiom) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-disposeAxiom| common-lisp-user::args))
  (owlapi-defun (owlapi-dispose) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-dispose| common-lisp-user::args))
  (owlapi-defun (owlapi-disable-transient-axiom-mode)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-disableTransientAxiomMode|
           common-lisp-user::args))
  (owlapi-defun (owlapi-disable-simplified-protocol)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-disableSimplifiedProtocol|
           common-lisp-user::args))
  (owlapi-defun (owlapi-disable-memory-saving-mode)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-disableMemorySavingMode| common-lisp-user::args))
  (owlapi-defun (owlapi-disable-lookup-mode)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-disableLookupMode| common-lisp-user::args))
  (owlapi-defun (owlapi-disable-incremental-updates)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-disableIncrementalUpdates|
           common-lisp-user::args))
  (owlapi-defun (owlapi-disable-auto-mode)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-disableAutoMode| common-lisp-user::args))
  (owlapi-defun (owlapi-describe-reasoners)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-describeReasoners| common-lisp-user::args))
  (owlapi-defun (owlapi-describe-reasoner)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-describeReasoner| common-lisp-user::args))
  (owlapi-defun (owlapi-describe-ontology)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-describeOntology| common-lisp-user::args))
  (owlapi-defun (owlapi-describe-ontologies)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-describeOntologies| common-lisp-user::args))
  (owlapi-defun (owlapi-contains) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-contains| common-lisp-user::args))
  (owlapi-defun (owlapi-consider-declarations)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-considerDeclarations| common-lisp-user::args))
  (owlapi-defun (owlapi-clear-registry) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-clearRegistry| common-lisp-user::args))
  (owlapi-defun (owlapi-clear-ontologies)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-clearOntologies| common-lisp-user::args))
  (owlapi-defun (owlapi-clear-changes) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-clearChanges| common-lisp-user::args))
  (owlapi-defun (owlapi-classify) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-classify| common-lisp-user::args))
  (owlapi-defun (owlapi-batch-synchronize)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-batchSynchronize| common-lisp-user::args))
  (owlapi-defun (owlapi-auto-remove-axioms-from)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-autoRemoveAxiomsFrom| common-lisp-user::args))
  (owlapi-defun (owlapi-auto-batch-remove-axioms-from)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-autoBatchRemoveAxiomsFrom|
           common-lisp-user::args))
  (owlapi-defun (owlapi-auto-batch-add-axioms-to)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-autoBatchAddAxiomsTo| common-lisp-user::args))
  (owlapi-defun (owlapi-auto-apply-changes)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-autoApplyChanges| common-lisp-user::args))
  (owlapi-defun (owlapi-auto-add-axioms-to)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-autoAddAxiomsTo| common-lisp-user::args))
  (owlapi-defun (owlapi-apply-changes) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-applyChanges| common-lisp-user::args))
  (owlapi-defun (owlapi-advance-progress)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-advanceProgress| common-lisp-user::args))
  (owlapi-defun (owlapi-add-prefix) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-addPrefix| common-lisp-user::args))
  (owlapi-defun (owlapi-abort) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-abort| common-lisp-user::args))
  (owlapi-defun (owlapi-set-ontology-uri)
                (&rest common-lisp-user::args)
    (apply #'|OWLAPI-SetOntologyURI| common-lisp-user::args))
  (owlapi-defun (owlapi-remove-axioms) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-RemoveAxioms| common-lisp-user::args))
  (owlapi-defun (owlapi-remove-axiom) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-RemoveAxiom| common-lisp-user::args))
  (owlapi-defun (owlapi-id-to-axiom) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-IDToAxiom| common-lisp-user::args))
  (owlapi-defun (owlapi-axiom-to-id) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-AxiomToID| common-lisp-user::args))
  (owlapi-defun (owlapi-axiom-loaded?) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-AxiomLoaded?| common-lisp-user::args))
  (owlapi-defun (owlapi-add-axioms) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-AddAxioms| common-lisp-user::args))
  (owlapi-defun (owlapi-add-axiom) (&rest common-lisp-user::args)
    (apply #'|OWLAPI-AddAxiom| common-lisp-user::args)))